### ISSUE TITLE
IE issues

### ISSUE THREAD

**Issue by GoogleCodeExporter** [OpenAero/main#159]
```
IE has many issues. Solving will take a lot of work. Issues can be added below.
```

Original issue reported on code.google.com by `openaero...@gmail.com` on 6 Oct 2014 at 8:21

**Comment by OpenAero** [comment]
When selecting "Print/save forms" from the File menu, the "Print options" form
show up correctly, but when clicking on the "Print/Save PDF" button nothing
happens.
Also when clicking on the "Save PNG image" an error message is displayed telling
that the PNG conversion failed. "Save SVG image" seems to work correctly.
This bug has not appeared with the last release, but is present in several of
the previous releases.

**Comment by OpenAero** [comment]
Closing issue as IE is being replaced by Edge which is much more standards compliant
