### ISSUE TITLE
Embed sequence in PNG using steganography

### ISSUE THREAD

**Issue by GoogleCodeExporter** [OpenAero/main#168]
```
On iOS, only images can be opened from the file menu. For this reason, Open 
Sequence was disabled in OpenAero 1.5.0.
Using steganography it may be possible to embed the sequence in a PNG. This 
would be very convenient for iOS and also an elegant way to submit sequences as 
a "preview" (the PNG image) would be included.

http://www.peter-eigenschink.at/projects/steganographyjs/
```

Original issue reported on code.google.com by `openaero...@gmail.com` on 5 Jan 2015 at 2:23

**Comment by OpenAero** [comment]
As of iOS 9, opening files from Dropbox and other file providers is supported. This provides sufficient file opening support on iOS.
On OpenAero 2016.2 it is possible to use Open Sequence on iOS.
Closing issue.
