### ISSUE TITLE
Printing layout problem

### ISSUE THREAD

**Issue by orfanic** [OpenAero/main#176]
Printing scale and borders are not scaled to have full page printing. 
![screen1](https://cloud.githubusercontent.com/assets/7349024/6960762/b2f96ba8-d925-11e4-9953-d2aef4dab5bf.png)

To reproduce: File->Print->Print

Version: 1.5.1.4, browser Chrome 41.0.2272.118 m, Win 7 SP1 x64

Remark: It works perfectly in current devel.openaero.net version 1.5.1.4

**Comment by djmolny** [comment]
Same problem on 1.5.1.4 with Chrome 41.0.2272.118 on both Ubuntu 14.04 and Win 8.1 x64.

**Comment by fj40cruzer** [comment]
Same with Yosemite using firefox, safari, and chrome

**Comment by OpenAero** [comment]
The issue should be resolved in OpenAero 1.5.1.5. Please confirm.

**Comment by orfanic** [comment]
Working smoothly now. Confirmed.

Vladimir.
