### ISSUE TITLE
Display Aircraft Type on Forms B&C

### ISSUE THREAD

**Issue by djmolny** [OpenAero/main#177]
Under "Aircraft Type and Registration", I entered "Giles G-200 N220DJ". On the B&C forms the registration number ("N220DJ") appeared in the "A/C" area on the right-hand edge of the pages.

Judges can't read a registration number on an aircraft that could be nearly a mile away. The aircraft type should be displayed instead.

**Comment by OpenAero** [comment]
Fixed in 1.5.1.6
