### ISSUE TITLE
Printing

### ISSUE THREAD

**Issue by fj40cruzer** [OpenAero/main#179]
Using . . .
1. Using chrome, print window will popup then immediately disappear, so printing isn't even possible with chrome.
2. In both Safari and Firefox, the A-B-Cs are about 1/2 size, but when scaled up, will not stay centered on the page. 
3. Saving as PDF yields the same problem as printing. 
4. Even if I could print a form that was the correct size, the point/figure listing is on the B-C cards, is there a way to remove this?

Using MBP on Yosemite, and have tried latest version of Chrome, Safari, and Firefox.

**Comment by OpenAero** [comment]
Both issues should be resolved in OpenAero 1.5.1.5. Please confirm.

**Comment by orfanic** [comment]
Working smoothly. Confirmed on my side.

Vladimir.
