### ISSUE TITLE
Set 'Add Super Family numbers' as default for printing Free's

### ISSUE THREAD

**Issue by nickbuck** [OpenAero/main#181]
The 'Super Family numbers' check-box has to be reset to ensure that Free's are printed / pdf'd with the SF numbers showing, which is essential for anyone entering data into a scoring programme. This should be the auto-default setting whenever Free's are being handled. It's really annoying to get pilots Free's as pdf's with no SF's - they are essential when entering the sequence K factors for pilots Free's in ACRO ...

**Comment by OpenAero** [comment]
This is already default behaviour. Checked again by developer.
Could you provide an example of a workflow where this does not work correctly?

**Comment by OpenAero** [comment]
Closing issue as this seems to work fine.
