### ISSUE TITLE
IAC Floating Point

### ISSUE THREAD

**Issue by heyyouguesswho** [OpenAero/main#182]
Trying to finish an IAC Sequence for a colleague.  Unable to locate any feature supporting Floating Point calculation for a Sportsman Freestyle.  Didn't find any support in the manual, nor did I find any note of this while searcing the developer Wiki.  If this is a feature to be added with IAC Rules Import; what is the estimated date to complete?

Floating Point allows the user to adjust the sequence 'K' factor if it exceeds the max allowable.  The highest value figure in the sequence may be reduced by 1K to align with category criteria.  In this case the student's design is 131K with a maximum value of 130K for 2015 IAC Sportsman.  Floating Point will fix this discrepancy.

**Comment by OpenAero** [comment]
Will check with IAC rule developer

**Comment by OpenAero** [comment]
Fixed in 1.5.1.8
