### ISSUE TITLE
Rule Error in Glider UNL / ADV Free

### ISSUE THREAD

**Issue by AcroDirki** [OpenAero/main#184]
Hi guys!

I think to have encountered a mistake in the rule checking concerning the FREE in Glider UNL and ADV Programmes, using OpenAero 1.5.1.8.:

The routine does not alert a repitition of exact catalogue numbers for hesitation rolls, snap rolls and spins. According to sporting code section 6 part II (2015-2) ch. 4.3.3.1. a) such a repitition is prohibited.

Could you please fix this bug within 2 weeks (beginning of W(A)GAC)?

Best regards,
D.

**Comment by OpenAero** [comment]
Hi D.,

Thank you for your bug reports. I will make sure all bugs are fixed before
the 25th and try to add some of the suggested improvements too.

Regards,
Ringo

Op zaterdag 18 juli 2015 heeft AcroDirki <notifications@github.com> het
volgende geschreven:

**Comment by OpenAero** [comment]
Fixed in 1.5.2

**Comment by AcroDirki** [comment]
Great work, Ringo! Thank you a lot!
