### ISSUE TITLE
FREE UNKNOWN DESIGNER

### ISSUE THREAD

**Issue by AcroDirki** [OpenAero/main#185]
Hi guys,

I've had a quick look on the free unknown designer. Great Work!

1. A mini form A on the right side of the screen would be helpful to see the Total K.

2. A little bug occurs after the following misshandling:

When I drag and drop a linking figure into the sequence and I then choose a single line (1.1.1.1) as a linking figure and I then click on the symbol for flipping the roll direction in the figure editor, without having chosen a roll, the figure disappears in the sequence, but is still counted as linking figure. Then no linking figures are shown in the sequence but one is counted. Please try to reproduce this for better undestanding.

3. For the selection of linking figures in the free unknown designer, the command line would be a nice alternative. The substrings created by the free unknown designer could be highlighted in this command line with grey colour, for example...

Best regards,
D.

**Comment by OpenAero** [comment]
Thanks for the compliment!

Regarding the first issue; I'm not sure what the benefit of a mini Form A would be. The submitted figures  can not be changed so their K is fixed. The Linking figures will always add up to the same K (currently 24), independent of the amount and complexity of the Linking figures.

The other issues should be resolved in the devel version of OpenAero 1.5.2 at http://devel.openaero.net . When confirmed, this version can be released as official.

**Comment by OpenAero** [comment]
Issues 2 & 3 have been resolved/added.
Is there a reason to include the mini form A in the Free Unknown Designer? If not, this issue will be closed.

**Comment by AcroDirki** [comment]
For  now I have no good reason other than this:
Maybe some pilots / competitors want to arrange their free unknown figures due to tactical issues with the highest figures k first or probably last, if there are more than one proper solutions. However, a mini form A would provide a quick overview for the figures assembly...

Best regards,
D.

**Comment by OpenAero** [comment]
The K factors (mini form A) is adressed in Free Known Designer, Issue #199 .
This will be closed and merged.
