### ISSUE TITLE
Bug during color inversion for printouts

### ISSUE THREAD

**Issue by AcroDirki** [OpenAero/main#186]
Hi guys,

another bug encountered when printing a pilots card with inversed colors:

All figure comments are not inverted to white color.
Furthermore, the text font of the figure comments is changed to Times or sth. similar from the specified and shown text font of the screen.

Best regards,
D.

**Comment by OpenAero** [comment]
Fixed in 1.5.2 by using setAttribute in makeTextBlock. Also fixed font line height and scaling issues
