### ISSUE TITLE
check routine for unknown figure proposal

### ISSUE THREAD

**Issue by AcroDirki** [OpenAero/main#187]
Hi guys,

the check routine for the unknown figure proposals (Unknown0) accounts for the rules, specified in section 6 part II (2015-2) ch. 4.3.4.2 a), b) and d), but not c).
Assuming, the contest director provides convenient input of figure proposals by assigning the NACs to the proposed figures, it should be possible to establish a routine, which accounts for this rule.

Best regards,
D.

**Comment by OpenAero** [comment]
Any routine that handles this would have to do combination checks on:
- figure comment holding the flag code
- figure aresti number (for entry/exit reverse)
- K summation
This is not possible from the current rule checking system. So there are two options:
1) expand the checking system to allow these kinds of rules, preferably in a generic way that enables other uses
2) hardcode this check into OpenAero itself
Option 2 is not preferable as the hardcoded rules should be kept to a minimum. This rule is not difficult to check by hand and is only applicable for a small subset of aerobatic competition.
Option 1 would require thorough consideration and a considerable programming effort.

**Comment by AcroDirki** [comment]
I suppose that the most programming effort comes along due to the check of the entry/exit reverse. Maybe, a substep could reduce this effort provisionally:
The figure proposal is performed in the grid view. Another view option, which filters or groups the proposed figures according to the NAC, could give a convenient overview of the proposal. K summation check could be done after that grouping...

The hardcode option I do not understand entirely...

**Comment by OpenAero** [comment]
In OpenAero all rules are coded in special files; see https://github.com/OpenAero/main/wiki/Developers#Creating_rule_checking_files for an explanation.
This makes maintaining rules easier and prevents having to code rules in the main OpenAero software. However there is currently no rule checking system available that allows coding of this rule in the rule checking files.

As a workaround, I have added a rule that creates an Alert stating a manual check of the specified rule is required.

**Comment by OpenAero** [comment]
Closing this issue as a pure software solution is too difficult whereas manual checking is quite easy.
