### ISSUE TITLE
Unable to get oposite rolls when first is super slow roll.

### ISSUE THREAD

**Issue by orfanic** [OpenAero/main#190]
It is impossible to get oposite roll after super slow roll. Sequence is ignoring oposite roll input.
- To replicate the error try 02,2- or -02,2. Same is happening within other types of base figures.
- When slow roll is first and super slow roll second it behaves normaly.
- Version 1.5.1.8, Google Chrome 44.0.2403.107 m

**Comment by AcroDirki** [comment]
Try 02,,2 or -02,,2- or 2,,02 or -2,,02-  ;)

**Comment by OpenAero** [comment]
Fixed in OpenAero 1.5.2, which is now available (app may take several hours)
