### ISSUE TITLE
link 

### ISSUE THREAD

**Issue by teodormunteanu** [OpenAero/main#191]
Under the Regulationis is not specified that the link figures may not be placed to the beginning of the sequence, but there is such a restriction in the program.

**Comment by OpenAero** [comment]
Unable to replicate this restriction.
To be clear:
When using the Free Unknown Designer to add a Link figure, the warning
"Illegal figure" will be shown until an actual figure has been chosen for
the link.

Op zondag 26 juli 2015 heeft teodormunteanu <notifications@github.com> het
volgende geschreven:

**Comment by teodormunteanu** [comment]
that worning does not disappear after I entered the figure link. I solved
the problem by deleting the figure code manually , then reintroduced
the figure in normal program designer.

**Comment by OpenAero** [comment]
Unfortunately I can't replicate the issue as I don't understand exactly in
which way it doesn't work.
Could you give a step by step description of the problem? Preferably by
using the exact text from the software and where necessary screenshots?

Op maandag 27 juli 2015 heeft teodormunteanu <notifications@github.com> het
volgende geschreven:

> that worning does not disappear after I entered the figure link. I solved
> the problem by deleting the figure code manually , then reintroduced
> the figure in normal program designer.
>
> On Sun, Jul 26, 2015 at 11:10 AM, OpenAero <notifications@github.com

**Comment by teodormunteanu** [comment]
these are the figures proposed for the program unknown in the advanced
championship . this is the program proposed by a country. When I tried to
put the first figure as a link figure, I got error that figure is illegal.
After entering all fugurile, I give "free finalize unk. Designer" I get an
error about this issue, after that, in normal designer, the link figure is
as error figure with a red diagonal square. Solving this problem is to
delete the figure code and add it again.

http://openaero.net?s=PHNlcXVlbmNlPgogIDxjYXRlZ29yeT5BZHZhbmNlZDwvY2F0ZWdvcnk-CiAgPGNsYXNzPnBvd2VyZWQ8L2NsYXNzPgogIDxwcm9ncmFtPlVua25vd24xPC9wcm9ncmFtPgogIDxydWxlcz5DSVZBPC9ydWxlcz4KICA8cG9zaXRpb25pbmc-MzA8L3Bvc2l0aW9uaW5nPgogIDxzZXF1ZW5jZV90ZXh0PiJATCIgLzItICJAQyIgLTJ0Li4nMmYuK35-ICJARiIgbzg4ICJASCIgYi4uLicyNCcnK2AgIkBBIiBvNmYtICJAQiIgLTgsM21mOzQ4ICgwLDE3KSAiQEQiIGgzICgwLDYpICJASiIgLDJwYi4nLDQgIkBMIiB2JycgIkBJIiAuLi42cy4uaWs0NGBgYH5-ICJATCIgMTElIGBgKzJhK2BgYCAiQEciIDMlIGBgYGBgYGBgMjRgcmM0NCtgYGAgKDAsNikgIkBMIiBtMiAoMCwxNCkgIkBFIiAtMSUgNmMyZi08L3NlcXVlbmNlX3RleHQ-CiAgPGxvZ28-Q0lWQTwvbG9nbz4KICA8b2FfdmVyc2lvbj4xLjUuMjwvb2FfdmVyc2lvbj4KPC9zZXF1ZW5jZT4
<http://openaero.net/?s=PHNlcXVlbmNlPgogIDxjYXRlZ29yeT5BZHZhbmNlZDwvY2F0ZWdvcnk-CiAgPGNsYXNzPnBvd2VyZWQ8L2NsYXNzPgogIDxwcm9ncmFtPlVua25vd24xPC9wcm9ncmFtPgogIDxydWxlcz5DSVZBPC9ydWxlcz4KICA8cG9zaXRpb25pbmc-MzA8L3Bvc2l0aW9uaW5nPgogIDxzZXF1ZW5jZV90ZXh0PiJATCIgLzItICJAQyIgLTJ0Li4nMmYuK35-ICJARiIgbzg4ICJASCIgYi4uLicyNCcnK2AgIkBBIiBvNmYtICJAQiIgLTgsM21mOzQ4ICgwLDE3KSAiQEQiIGgzICgwLDYpICJASiIgLDJwYi4nLDQgIkBMIiB2JycgIkBJIiAuLi42cy4uaWs0NGBgYH5-ICJATCIgMTElIGBgKzJhK2BgYCAiQEciIDMlIGBgYGBgYGBgMjRgcmM0NCtgYGAgKDAsNikgIkBMIiBtMiAoMCwxNCkgIkBFIiAtMSUgNmMyZi08L3NlcXVlbmNlX3RleHQ-CiAgPGxvZ28-Q0lWQTwvbG9nbz4KICA8b2FfdmVyc2lvbj4xLjUuMjwvb2FfdmVyc2lvbj4KPC9zZXF1ZW5jZT4>

**Comment by OpenAero** [comment]
Thank you for the explanation.

The following method works:
After adding the link at the beginning, tap the Link to select it ( in the
Free Unknown designer). Then a figure can be chosen from the Figure
chooser. This will make the "Illegal figure" warning disappear.
Op 27 jul. 2015 12:24 schreef "teodormunteanu" <notifications@github.com>:

> these are the figures proposed for the program unknown in the advanced
> championship . this is the program proposed by a country. When I tried to
> put the first figure as a link figure, I got error that figure is illegal.
> After entering all fugurile, I give "free finalize unk. Designer" I get an
> error about this issue, after that, in normal designer, the link figure is
> as error figure with a red diagonal square. Solving this problem is to
> delete the figure code and add it again.
>
>
> http://openaero.net?s=PHNlcXVlbmNlPgogIDxjYXRlZ29yeT5BZHZhbmNlZDwvY2F0ZWdvcnk-CiAgPGNsYXNzPnBvd2VyZWQ8L2NsYXNzPgogIDxwcm9ncmFtPlVua25vd24xPC9wcm9ncmFtPgogIDxydWxlcz5DSVZBPC9ydWxlcz4KICA8cG9zaXRpb25pbmc-MzA8L3Bvc2l0aW9uaW5nPgogIDxzZXF1ZW5jZV90ZXh0PiJATCIgLzItICJAQyIgLTJ0Li4nMmYuK35-ICJARiIgbzg4ICJASCIgYi4uLicyNCcnK2AgIkBBIiBvNmYtICJAQiIgLTgsM21mOzQ4ICgwLDE3KSAiQEQiIGgzICgwLDYpICJASiIgLDJwYi4nLDQgIkBMIiB2JycgIkBJIiAuLi42cy4uaWs0NGBgYH5-ICJATCIgMTElIGBgKzJhK2BgYCAiQEciIDMlIGBgYGBgYGBgMjRgcmM0NCtgYGAgKDAsNikgIkBMIiBtMiAoMCwxNCkgIkBFIiAtMSUgNmMyZi08L3NlcXVlbmNlX3RleHQ-CiAgPGxvZ28-Q0lWQTwvbG9nbz4KICA8b2FfdmVyc2lvbj4xLjUuMjwvb2FfdmVyc2lvbj4KPC9zZXF1ZW5jZT4
> <
> http://openaero.net/?s=PHNlcXVlbmNlPgogIDxjYXRlZ29yeT5BZHZhbmNlZDwvY2F0ZWdvcnk-CiAgPGNsYXNzPnBvd2VyZWQ8L2NsYXNzPgogIDxwcm9ncmFtPlVua25vd24xPC9wcm9ncmFtPgogIDxydWxlcz5DSVZBPC9ydWxlcz4KICA8cG9zaXRpb25pbmc-MzA8L3Bvc2l0aW9uaW5nPgogIDxzZXF1ZW5jZV90ZXh0PiJATCIgLzItICJAQyIgLTJ0Li4nMmYuK35-ICJARiIgbzg4ICJASCIgYi4uLicyNCcnK2AgIkBBIiBvNmYtICJAQiIgLTgsM21mOzQ4ICgwLDE3KSAiQEQiIGgzICgwLDYpICJASiIgLDJwYi4nLDQgIkBMIiB2JycgIkBJIiAuLi42cy4uaWs0NGBgYH5-ICJATCIgMTElIGBgKzJhK2BgYCAiQEciIDMlIGBgYGBgYGBgMjRgcmM0NCtgYGAgKDAsNikgIkBMIiBtMiAoMCwxNCkgIkBFIiAtMSUgNmMyZi08L3NlcXVlbmNlX3RleHQ-CiAgPGxvZ28-Q0lWQTwvbG9nbz4KICA8b2FfdmVyc2lvbj4xLjUuMjwvb2FfdmVyc2lvbj4KPC9zZXF1ZW5jZT4
> >
>
> On Mon, Jul 27, 2015 at 11:12 AM, OpenAero <notifications@github.com>
> wrote:
>
> > Unfortunately I can't replicate the issue as I don't understand exactly
> in
> > which way it doesn't work.
> > Could you give a step by step description of the problem? Preferably by
> > using the exact text from the software and where necessary screenshots?
> >
> > Op maandag 27 juli 2015 heeft teodormunteanu <notifications@github.com>
> > het
> > volgende geschreven:
> >
> > > that worning does not disappear after I entered the figure link. I
> solved
> > > the problem by deleting the figure code manually , then reintroduced
> > > the figure in normal program designer.
> > >
> > > On Sun, Jul 26, 2015 at 11:10 AM, OpenAero <notifications@github.com

**Comment by OpenAero** [comment]
Fixed in 1.5.2.2 by making sure the Figure chooser is also opened when using a link as Figure 1
