### ISSUE TITLE
General Issue on Figure / Sequence Comments

### ISSUE THREAD

**Issue by AcroDirki** [OpenAero/main#192]
Hi guys!

This issue does not hurry.
The figure comments are a nice opportunity to include additional information to the figures and the entire sequence. As OpenAero could (and should) be used within the state-of-the-art aerobatic education :) , these comments could play an - probably till now - underestimated role. Especially in glider aerobatics, they could be used to display the planned or ideal energy management for example in terms of entry and exit heights and speeds of each figure.
Unfortunately, the positioning and styling options of these comment-boxes are still - lets say - basic. It should be possible to comment beside the figure entry every roll-element as well. These roll-element comments could probably be adressed in the string by ¨@1:  1st roll coment @2: 2nd roll comment" 1c2 and should be supported throughout the figure editor menu accordingly.

Side information:
The german glider aerobatic section within the german aeroclub, DAeC, thinks about to implement a  course on basic understanding of OpenAero to the guidelines for the theoretical part (5 hours required) of the aerobatic education, which has been strengthend up due to FCL regulations.

Best regards,
D.

**Comment by OpenAero** [comment]
Expanding the comment box options is certainly interesting.
Currently, adding comments to rolls is already supported by prefixing the roll with the comment. Try:
"Pull immediate after"1c"Halfway line"2
These comments can also be added/edited in the comment box after each roll in the Figure Editor. Currently they do not support the special options from the regular comments such as newlines.

Which additional options do you think would be most useful?

**Comment by AcroDirki** [comment]
Oh, I wasn't aware of this fact.
Well, it's hard to give a full awnser on that question, but I think, that even for the roll comments the new line option could be useful. Another feature could be, that the figure entries and exit comments could be alligned to the entry and exit line, right after the starting symbol and right before the ending symbol. Then, the commented sequence wouldn't look so blown up compared to the uncommented sequence. Text size and sizing of these comments doesn't work proper.
Further it could be useful to place comments right of the entire sequence, which are not assigned to a certain figure.
Another feature for teaching issues could be a marker or highlighting function, which highlights certain parts of a figure e.g. the part of the vertical line after the role.
Eventually, I think, that all such features must be accessible from the left hand menu as most of the users do not use the command line.

Best regards,
D.

**Comment by OpenAero** [comment]
Many of these options are difficult to implement in a consistent way. Most comments/highlights etc could easily be added to a sequence with PDF or image editing software.
Moving this issue to Low Priority.

**Comment by AcroDirki** [comment]
Agree that it may be difficult. However, image editing software doesn´t appear to be feasible to the intention of live-teaching.

Currently, text annotations like "R" on rolling circles' arrows are not possible, but would be appreciated.

**Comment by OpenAero** [comment]
This will not be pursued to prevent "feature creep".
