### ISSUE TITLE
Wrong Alert on Connecting Figures in CIVA Glider Unknown1

### ISSUE THREAD

**Issue by AcroDirki** [OpenAero/main#193]
Hi guys,

OpenAero 1.5.2 reports alert, when a connecting figure assigned with "@L" is added to the 1st unknown sequence, which must be composed by 7 given figures and max. 2 additional connecting figures, where the K's of these connecting figures are maintained acc. to Section 6 part II Ch. 4.3.4.5.

If possibile, please fix immediately!

Best regards,
D.

**Comment by OpenAero** [comment]
Unable to replicate. Which alert do you mean exactly?
Op 5 aug. 2015 20:03 schreef "AcroDirki" <notifications@github.com>:

**Comment by AcroDirki** [comment]
Set Civa glider rules for advanced unknown 1. Insert 7 figures and somewhere one additional connectiing figure assigned by "@L". Then the wrong alert is reported.

**Comment by AcroDirki** [comment]
Alert was: Maximum of 0 connecting figures allowed.

**Comment by OpenAero** [comment]
For some reason this problem did not show up the first time I checked, but
it did now.
Unfortunately I won't be able to have a fix online until Sunday.

**Comment by OpenAero** [comment]
According to Section 6 part II Ch. 4.3.4, the linking figures in the Unknown sequences are counted with their normal K factor, with the exception of the Free Unknown. Also, these linking figures do not need to be marked.
Currently OpenAero uses the @L designation for adjusting K factors, as is done in the CIVA Power and Glider Free Unknowns. This is in accordance with the rules and works as it should.
Is there a necessity for expanding this to include Unknowns where the k does not need to be adjusted (programme 3, 5 and 6 for Glider)?

**Comment by OpenAero** [comment]
Closing issue: software performs as required
