### ISSUE TITLE
Add support for IAC Unlimited

### ISSUE THREAD

**Issue by djmolny** [OpenAero/main#195]
Currently the only way to compose an Unlimited sequence is to specify CIVA rules. This causes two problems: incorrect Presentation K factor (40 for CIVA, 26 for IAC) and the use of CIVA form templates which contravenes IAC rule 6.16(a): "Sequence is drawn on current IAC forms as depicted in Appendix 7 of this rule book."

**Comment by OpenAero** [comment]
K factor can be adjusted in the Sequence Info. Print template can be
changed to IAC in the Print dialog.
However, will add IAC Unlimited to next version of OpenAero for automatic
selection.
Op 19 aug. 2015 18:46 schreef "DJ Molny" <notifications@github.com>:

**Comment by OpenAero** [comment]
Fixed in 1.5.2.2
