### ISSUE TITLE
Known Free Designer

### ISSUE THREAD

**Issue by AcroDirki** [OpenAero/main#199]
Hi guys,

Probably this idea is already on your ToDo-List.
Last season the innovation of the free unknown designer was in my eyes most impressive to the users as it was easy and quickly to apply. As the concept of the known free sequence requires a similar process, the idea is near to apply such a 'designer'-functionality for this sequence, rather than using the Queue-process. Additional Figures could be assigned by "@P" (private) instead of "@L" to probably simplyfy (even manual) sequence checking.

So far, the devel-team has earned a huge compliment again for the implementation of the 2016 rules in a felt record time. Great work!

Best regards!

**Comment by OpenAero** [comment]
This issue has been under discussion and should be implemented soon.

Adding a code to the Free figures should not be needed as any figure that does not have a letter is a Free figure AND will retain it's original K factor.

The Free Unknown designer has to be adjusted at least on the following points:
- assure a user is asked to start the Free Known designer when opening Free Known figures file
- rename designer and wording
- change "Additional" (previously LINK) to "Free", including usage count
- include Free figures in rule checking
- add a K list to the right of every subsequence block, e.g.:
  23
  19
  21
  ---
  63
- show Max total K somewhere

**Comment by OpenAero** [comment]
Implemented in 2018.1
