### ISSUE TITLE
Export sequence to YSFlight replay format (.YFS)

### ISSUE THREAD

**Issue by Symbian9** [OpenAero/main#203]
Please, add support for export sequence to YSFlight - free and smart flight simulator game.
http://ysflight.org
As this game work on all OS, support OpenGl1, OpenGL2, DirectX and have small size it could be good visulization tool specially for OpenAero and OLAN notations (after converting to YFS)
YFS file format is flight replay file, that include all maneuros for specifed time moments (like "black box").
- https://forum.ysfhq.com/viewtopic.php?t=8007
- https://forum.ysfhq.com/viewtopic.php?t=8174
- https://forum.ysfhq.com/viewtopic.php?p=28861

<b>VIDEO PREVIEW</b>
- https://www.youtube.com/watch?v=JT_mvKac9q4
- https://www.youtube.com/watch?v=_RpxJcG--Mo
- https://www.youtube.com/watch?v=GzujDnSlsow

![YSFlight Aerobatic 1](http://i.imgur.com/TK2m8dp.png)
![YSFlight Aerobatic 2](http://i.imgur.com/JZE8D.png)
![YSFlight Aerobatic 3](http://i.imgur.com/RIkMc.png)

OpenAero topic https://forum.ysfhq.com/viewtopic.php?t=8203

**Comment by OpenAero** [comment]
No plans to implement at any time. Closing issue.
