### ISSUE TITLE
Fix "leftBlock" width

### ISSUE THREAD

**Issue by Symbian9** [OpenAero/main#206]
Currently OpenAero has an bad look of left block menu (original width = 276px)

I propose fix it: only need increase this width to 290px

**Comment by OpenAero** [comment]
Simple changing the width would not look nice without a scrollbar present.
Fixed by adding a container around leftBlock which contains the scrollbar when present and is transparent otherwise.
Please verify on http://devel.openaero.net

**Comment by Symbian9** [comment]
I will try check it, but anyway it bettrer way is optimiyzing of leftBox and design in way wen it no need scrolling (in desktop mode)

**Comment by OpenAero** [comment]
Certainly it would be good to reduce the need for scrolling. On modern desktops with reasonable resolutions (mine is 1400x1050) scrolling is only occasional, except when many alerts are present.

Do you have suggestions on how to optimize the Figure Editor (which can become larger than Sequence Info) without crowding it more? Also any optimizing should not lead to more click actions for the user when editing figures.

**Comment by OpenAero** [comment]
Closing this specific issue. May be part of future redesign.
