### ISSUE TITLE
Free Known Alerts

### ISSUE THREAD

**Issue by PhilBurgessAerobatics** [OpenAero/main#209]
Hi,

Congratulations on developing such an excellent tool for producing aerobatic sequences! 

Are there any current issues with the sequence checker that are currently being investigated? When using the sequence checker to verify my Power, CIVA, Unlimited, Free Known, the alerts display contains the following alerts regardless of the figures that I chose. Also other deliberate mistakes are not alerted:

At least 10 base figs req
at least 2 neg snap req
at least 1 family1 req
at least 1 family 6 req
(1) max additional figs allowed 0
(3) max additional figs allowed 0
(7) max additional figs allowed 0
(8) max additional figs allowed 0

I have noticed the same error on several different computers and an android mobile.

Regards
Phil Burgess
www.philburgessaerobatics.com

**Comment by OpenAero** [comment]
Hi Phil,

This is not a known issue. Could you email the sequence (as a link or .seq
file) to openaero.devel@gmail.com? This will help me track the problem.

Regards,
Ringo

Op wo 1 mrt. 2017 om 12:40 schreef PhilBurgessAerobatics <
notifications@github.com>

**Comment by PhilBurgessAerobatics** [comment]
Hi Ringo
Thank you for your reply. This may just be me using the application incorrectly however pasting this string in gets the same errors for me each time. (Power CIVA Unlimited Free known)
"@L" 22pbb(,7`),24''+~~ (0,0) "@A" 3% ````"|"5s,3''ib`````,3,2.'+` (0,0) "@L" .'',1'iw('').,5if,3..'' "@D" 2> +4,2fh5.'+++++~ "@E" ~+',22m'3if',7- (-10,13) "@C" -```````````,9iac(`6f``)3,5-```` (0,0) "@L" ~~--''8ta.''3f..++^ (0,0) "@L"
 3% ''6```w(,1)32- (-12,16) 2% -```````````,1iac(``22,2f`)+``` "@B" 2jio15-
Thanks for your assistancePhil Burgess 


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: OpenAero <notifications@github.com> Date: 07/03/2017  09:02  (GMT+00:00) To: OpenAero/main <main@noreply.github.com> Cc: PhilBurgessAerobatics <philburgessaerobatics@gmail.com>, Author <author@noreply.github.com> Subject: Re: [OpenAero/main] Free Known Alerts (#209) 
Hi Phil,



This is not a known issue. Could you email the sequence (as a link or .seq

file) to openaero.devel@gmail.com? This will help me track the problem.



Regards,

Ringo



Op wo 1 mrt. 2017 om 12:40 schreef PhilBurgessAerobatics <

notifications@github.com>

**Comment by OpenAero** [comment]
Hi Phil,

In the Free Known, the figures you add should *not* be marked as Additional
figures ("@L" in the figure string). Those are only for the Free Unknown.

So this should work fine:
22pbb(,7`),24''+~~ (0,0) "@A" 3% ````"|"5s,3''ib`````,3,2.'+` (0,0)
.'',1'iw('').,5if,3..'' "@D" 2> +4,2fh5.'+++++~ "@E" ~+',22m'3if',7-
(-10,13) "@C" -```````````,9iac(`6f``)3,5-```` (0,0) ~~--''8ta.''3f..++^
(0,0) 3% ''6```w(,1)32- (-12,16) 2% -```````````,1iac(``22,2f`)+``` "@B"
2jio15-

Regards,
Ringo

Op di 7 mrt. 2017 om 11:15 schreef PhilBurgessAerobatics <
notifications@github.com>

**Comment by PhilBurgessAerobatics** [comment]
Hi Ringo
Thank you for clarifying that. I have got it working now with no issues. Entirely my mistake! 
RegardsPhil Burgess 


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: OpenAero <notifications@github.com> Date: 07/03/2017  19:17  (GMT+00:00) To: OpenAero/main <main@noreply.github.com> Cc: PhilBurgessAerobatics <philburgessaerobatics@gmail.com>, Author <author@noreply.github.com> Subject: Re: [OpenAero/main] Free Known Alerts (#209) 
Hi Phil,



In the Free Known, the figures you add should *not* be marked as Additional

figures ("@L" in the figure string). Those are only for the Free Unknown.



So this should work fine:

22pbb(,7`),24''+~~ (0,0) "@A" 3% ````"|"5s,3''ib`````,3,2.'+` (0,0)

.'',1'iw('').,5if,3..'' "@D" 2> +4,2fh5.'+++++~ "@E" ~+',22m'3if',7-

(-10,13) "@C" -```````````,9iac(`6f``)3,5-```` (0,0) ~~--''8ta.''3f..++^

(0,0) 3% ''6```w(,1)32- (-12,16) 2% -```````````,1iac(``22,2f`)+``` "@B"

2jio15-



Regards,

Ringo



Op di 7 mrt. 2017 om 11:15 schreef PhilBurgessAerobatics <

notifications@github.com>
