### ISSUE TITLE
IAC Sportsman Free rule is incorrect

### ISSUE THREAD

**Issue by djmolny** [OpenAero/main#210]
OpenAero seems to check for *any* Family 7 figure in an IAC Sportsman Free. However the 2017 Rule Book requirement (page 6-3) is: "At least one figure from 7.2.1 thru 7.2.4, or 7.4.1 thru 7.4.6"

**Comment by OpenAero** [comment]
Should be fixed in 2017.1.1. Please confirm.

Op vr 3 mrt. 2017 om 00:04 schreef DJ Molny <notifications@github.com>

**Comment by djmolny** [comment]
Confirmed! Thanks for the fix. :-)
