### ISSUE TITLE
Max K is incorrect for 2017 IAC Sportsman Free 

### ISSUE THREAD

**Issue by djmolny** [OpenAero/main#211]
Per IAC rules, the maximum allowable K factor for a Sportsman Free program is the same as the current year's Known sequence. OpenAero currently says that the max allowable K is 127, should be 133 per https://www.iac.org/files/Sequences/SPTP-Known-2017.pdf

**Comment by OpenAero** [comment]
Thank you for the report. Should be solved in a few days.

Op ma 6 mrt. 2017 om 23:40 schreef DJ Molny <notifications@github.com>

**Comment by OpenAero** [comment]
Should be fixed in 2017.1.1. Please confirm.

Op ma 6 mrt. 2017 om 23:40 schreef DJ Molny <notifications@github.com>

**Comment by djmolny** [comment]
Confirmed! Thanks for the fix. :-)
