### ISSUE TITLE
2018 Advanced Free Known Figure 'A'

### ISSUE THREAD

**Issue by heyyouguesswho** [OpenAero/main#218]
There is a discrepancy with the direction of roll orientation on Advanced Free Known figures for 2018.  The International Aerobatic Club delegate to CIVA submitted a request to CIVA President Nick Buckenham who has subsequently replied with corrected documents showing proper direction of the rolls.

On the exit line of Figure 'A' for Power Advanced 2018, the 1-1/2 roll and full inside snap roll are to be executed in the SAME direction.  

Attached are the Check List for Advanced Power effective January 1.  I have also attached an amended Free Known Guidance document (version 3a) that was published on 7th of May 2018.  Both reflect the two rolling elements in same direction.

I know there has been correction issues where it was published both ways, but according to Nick's email and the supplied documents from CIVA administration the definitive guidance is to have same direction.  The library of figures for OpenAero presently depicts them as opposite of one another.

Thank you for your time and support - your software makes program construction very straight forward!

[CIVA Free Known Programme Check List Advanced Power 2018 v2.pdf](https://github.com/OpenAero/main/files/2006316/CIVA.Free.Known.Programme.Check.List.Advanced.Power.2018.v2.pdf)
[CIVA Free Known Programme Guidance - Power Aircraft 2018 v3a.pdf](https://github.com/OpenAero/main/files/2006317/CIVA.Free.Known.Programme.Guidance.-.Power.Aircraft.2018.v3a.pdf)

**Comment by OpenAero** [comment]
Fixed in 2018.3.1
