### ISSUE TITLE
Rules Update Glider Unknown0

### ISSUE THREAD

**Issue by AcroDirki** [OpenAero/main#221]
Hi guys,

OA gives back an alert, when the 5th positive flick roll is proposed. Same for negative flick and pos./neg. spins. Since 2015 there are overall 5 instead of 4 unknown programms to be flown. Hence, this alert needs to be updated that overall 5 of a kind may be allowed.

Kind regards,
D.

**Comment by OpenAero** [comment]
Fixed in 2018.3.2
