### ISSUE TITLE
Wrong Alert: "No opposite or unlinked rolls allowed", CIVA glider

### ISSUE THREAD

**Issue by AcroDirki** [OpenAero/main#222]
Hi guys!

When rules are set to CIVA glider UNL Unknown0, above error is indicated for:
id2f,if- ivs,2if and probably more figures. This rule is not up to date any more. Harmonization with actual sporting code is seen necessary.

Kind regards,
D.

**Comment by OpenAero** [comment]
I have been doing checking with the current rules and your remark seems correct. However, are you absolutely certain opposite flick rolls on descending lines are allowed? This is not allowed for Power Unlimited which, for obvious reasons, is usually much less restricted.

**Comment by OpenAero** [comment]
I'll also check this with CIVA as this changing this would allow figures that appear highly unwise to fly.

**Comment by AcroDirki** [comment]
Hi,
After reading, I´m sure in terms of what is published in the actual CIVA sporting code section 6 part II. :)
Further, above given examples have already been flown in the recent glider aerobatic world championships -  were hence accepted by Jury and CJ, also against few competitors' protests.

However, I understand that the given wording in section 6 part II is not very convenient for the programming of rules in OA and the rules are in my opinion still not complete to cover all potential safety issues (see at the end of this post). One reason more that especially these rules (A.2.1.1 to A.22.1.2 and also some in Appendix B) should be correctly implemented in OA.

What do you mean with "highly unwise to fly"? Do you refer to a certain wording in SC6pII? What example do you have in mind?
In principle, opposite or unlinked flicks on 45° descending lines or flicks following spins on 90° descending lines are not really an issue  on the governing competing glider types Swift, Fox & SZD59. (Of course it still requires certain flying skills.) However, there is no direct safety issue evident, as the flick/spin exit speed is for all of them reasonably below manoeuver speed, respectively the maximum recommended speed for flicks, and in glider aerobatics it is not required that the lines before and after flick rolls have a equal length (B.9.1.1.).

Few critics on CIVA-glider rules related to roll combinations:

1. A combination of 2 opposite or unlinked flicks of different type on a 90° descending line, I haven´t seen yet in glider aerobatics and it maybe borderline. However, it´s not explicitly forbidden.

2. Beside the flicks, SC6pII-2018-1 also allows that aileron rolls may follow spins (B.9.22.1, B.9.22.4.d), without defining then the maximum extent. A single half roll 90° downwards is allowed in UNL (not ADV) and not seen as a safety issue. A spin is allowed in both categories. A half roll following a spin is not explicitly forbidden [at least can´t find such a prohibition], but could easily be seen as a safety issue (due to relative high roll entry speed - usually half rolls 90° down are just flown in tailsides, stall turns or straight bumps).

3. While it is possible and allowed to fly a full aileron roll, followed by half a flick roll (opposite, unlinked), on a horizontal line, this wouldn´t be possible on descending lines, but it´s not forbidden by rules.

4. While it is possible and allowed to fly half a flick, followed by half a aileron roll on a horizontal line, this wouldn´t be possible on descending lines, but it is not forbidden.

5. While rule A.9.1.2 prohibits hesitation rolls in the apex of the negative loop 7.4.1.2 most probably for the reason of very high entry speed and high negative g before the roll element, a double-roll (9) in this apex is allowed, was proposed and flown in the last WGAC, which is just rediculous and undermines the rule completely.

Resumé:
Some of above given examples from the "field experience" show that the initial assumption of "healthy common sense" in designing these rules is proven to be wrong and it is comprehensive from the complexity of possible roll-combinations on the different lines that it is a very challenging, if not impossible, task for the CIVA-comittee to reasonably design rules against "strength-test-competitors". Unfortunately, too often protests and concerns on such figures are unheard or the protest doesn´t even take place due to shyness/uncertainty or sth else.

**Comment by OpenAero** [comment]
I think we agree on the fact that some of the figures that seem to be allowed in the current Glider rules are unsafe to fly. In Power Aerobatics this has been handled to a great extent by putting stringent limitations on roll/flick/spin combinations.
It seems this is not the case for Glider. I agree that OpenAero should strictly follow the rules and let discussions about this be handled by CIVA/Contest organisers.
In current OpenAero 2018.3.2 I have corrected the warning on vertical lines, allowing spin/roll/flick combinations (please check). I will wait a few days for response from CIVA and correct the other warnings too if there is no objection.

**Comment by AcroDirki** [comment]
Will do some spot checks. Currently in 2018.3.2 there is an issue with the grid box. It follows the mouse as soon the mouse is hovering on it. Can´t change the number of figures per grid line, as the mouse coursor doesn´t get there since the box is moved with the mouse movement...

**Comment by OpenAero** [comment]
This Grid box issue doesn't happen for me (Chrome 65.0). I made no changes to the Grid box.

**Comment by AcroDirki** [comment]
This also happens in the OpenAero App, downloaded with Chrome (Version 66.0.3359.139 (Offizieller Build) (64-Bit)) on Win10.

**Comment by AcroDirki** [comment]
First Spot Check - Roll Combinations on Horizontal Lines and Diagonal Down Lines; CIVA-Glider UNL UNKNOWN0):
In the grid, the issues/problematics are briefly described.
![horizontal and diagonal lines - roll combinations](https://user-images.githubusercontent.com/13392576/40505802-b1c65300-5f95-11e8-9e98-eb8a2aca8b4a.png)

**Comment by OpenAero** [comment]
Completed in 2018.3.3
