### ISSUE TITLE
Grid Info - Counting

### ISSUE THREAD

**Issue by AcroDirki** [OpenAero/main#224]
Hi guys,
Something is wrong in the counting. See attached image. There mist be a negative exit at high speed, but it is counted at low speed.
Kind regards,
D.

![screenshot_2018-05-16-21-17-07](https://user-images.githubusercontent.com/13392576/40139068-f840a5f8-594e-11e8-86d8-951850fcc9bf.png)

**Comment by OpenAero** [comment]
Fixed in 2018.3.1
