### ISSUE TITLE
"Manual Check for SC6pII 2.3.1.3 c)"

### ISSUE THREAD

**Issue by AcroDirki** [OpenAero/main#225]
Hi guys,

In order to aid in this manual check, OA should provide a button (preferably in the grid info box) to re-order the figure grid alphabetically due to the competing nations, assigned in the string.
Meanwhile, in the 2018-1 release this rule has moved to 2.3.1.2 c).

Kind regards,
D.

**Comment by OpenAero** [comment]
Feature added in 2018.3.3

**Comment by OpenAero** [comment]
Due to bugs, feature disabled in 2018.3.4. Will be enabled again when bugs are fixed.

**Comment by OpenAero** [comment]
Feature completed in 2018.3.6
