### ISSUE TITLE
Serious Bug in Glider Advanced

### ISSUE THREAD

**Issue by AcroDirki** [OpenAero/main#230]
Hi Ringo.
During the currently running german glider championship we have encountered the following problem beside few other minor issues:
When CIVA glider Advanced is selected (independent of the selected programme) all figures in every view setting disappear. Our provisional go-around is to use UNL rules and check in particular the free unknown manually. If you could fix it untill today 6 pm, 40 cpmpetitors will be impressed very much.
Kind regards, 
D.

**Comment by OpenAero** [comment]
Hi Dirk,

Unfortunately I am away, without laptop, until monday afternoon. You could
try the following:

- use the Chrome developer console to find the bug that occurs when loading
the rules
- get the rules file
https://github.com/OpenAero/main/blob/master/js/rules/rules18-glider-civa.js
and adjust where needed
- load adjusted rules through Tools menu

Good luck,
Ringo


Op zo 8 jul. 2018 12:11 schreef AcroDirki <notifications@github.com>:

**Comment by OpenAero** [comment]
Hi Dirk,

The issue has been fixed for use from openaero.net. Update for Android app
should be available tomorrow, for iOS app the next day.

Regards,
Ringo

Op zo 8 jul. 2018 om 13:05 schreef OpenAero Devel <openaero.devel@gmail.com

**Comment by OpenAero** [comment]
Issue fixed officially in 2018.3.8
