### ISSUE TITLE
Moving figures in normal view

### ISSUE THREAD

**Issue by OpenAero** [OpenAero/main#232]
This is a continuation of thread in Issue #219 that was under the wrong issue. Posts copied below:

Hi there, I've worked on two possible ways to rearrange figures in the editor.

One is in the figure editor, the buttons "<<" and ">>" move the current figure (including Comments, movements, etc) one figure further/back.

The other selecting to figure you want to move and simply start dragging a cross arrow handle left/right of the figure you want put it next to. (note currently there is such thing as a preview or a moving indicator yet, so don't wonder if nothing happens until you drop it).

See http://peter.turczak.de/openaero/ for a demo.

Please let me know your thoughts.
 @OpenAero
  Owner
 OpenAero commented 6 days ago • 
edited 
 The demo does look promising. Maybe it would be more simple to have two
blue arrows below a selected figure to move it back or forward. See rough
example image. Ideally this would only be one arrow for the first and last
figure.
Also, moving a figure to the first position should probably remove any
(xx,yy) and [xx,yy] moves as the first figure never has these.
![image](https://user-images.githubusercontent.com/11457953/42537953-b4683f8a-8496-11e8-8a16-1a35499294c4.png)
 @ptwz
  Contributor
ptwz commented 18 hours ago
Well, i tried to implement you suggestion, and for me it becomes very confusing to use. As long as the sequence only had one direction, this is an easy task to do. The arrow pointing right will move the figure further down the sequence when the sequence goes this direction. For example, after a stall turn, this would reverse. So clicking the "same" arrow would lead to a different thing to happen.

When designing a sequence, I find myself shuffeling around the figures quite far and often. So having to follow the figure and always clicking the proper button sometimes can be quite a pain. Especially when 90/270 deg. figure enties/exits are planned.

Therefore dragging the figure seems much more natural and easier for a user to understand. Otherwise having arrows in a fixed position, will ensure you understand what it will do at any given click but leads to more screen clutter.

**Comment by OpenAero** [comment]
I understand your remarks and the logic behind your original solution with a cross arrow handle. For user feedback it will be essential to show what happens when dragging the handle.
Best would be to:
* drag the figure with the handle
* show where the figure will be attached when handle is released. This could be done with a blue circle around start or end of figure to which it will be attached. The blue circle disappears when handle is released

Blue circle should show when within certain distance of start or end of figure. When mutiple are within this distance, pick closest.

Admittedly, the code for this is much more complex. However, for user experience it would be best.

**Comment by ptwz** [comment]
Thanks for the input. I've cobbled something together, which tries to visualize the dragging better and highlight the insertion point. Maybe you can have a look at it, it's not finished but shows the way I could imagine to go..

What is, in your opinion, the easiest way to get the start/endpoint of a figure? My way of determining is quite sub-optimal as of now.

**Comment by Dirk07** [comment]
Hi all,

I'd like to share my opinion to the topic, which is hopefully useful and dissolving confusion:

Before to much of draging and dropping arround (which is still a little bit tricky on tablets and smartphones) and cluttering the appearance, why not rather extend the higlighting feature, which appears in the canvas and the string-field already to the shown miniform A in form B/C view? Once the figure is also highlighted there, 2 arrows, one up and one down shall pop up in order to move the selected figure in the sequence order up or down. Isn't that easier to accomplish? These arrow-buttons must simply be associated with a string manipulation action (cutting out selected figur string, inserting again one delimitter before or after).

**Comment by OpenAero** [comment]
Thanks for this additional idea. First, I think it’s a good idea to extend the highlighting feature to the mini form A. This will improve clarity.
In principle I like the idea of using up and down buttons on mini form A. However, the mini form A is not always visible together with the sequence. For example, when using an iPad in portrait mode it often disappears right, requiring horizontal scrolling to come into view. Having mini form A always show, mostly for this feature, would give up valuable screen real estate.

**Comment by Dirk07** [comment]
Okay for Ipad and Smartphone I would propose then a page / column, containing the miniform A that can be swiped to the right edge, if not needed and swiped over the canvas, when needed to arrange the order.

**Comment by OpenAero** [comment]
The feature has now been implemented using a redesigned mini form A. Please check it at https://openaero.net/devel

**Comment by OpenAero** [comment]
Feature implementation completed in 2024.1.3
