### ISSUE TITLE
Change confusing "X-box" menu items

### ISSUE THREAD

**Issue by djmolny** [OpenAero/main#240]
Under the "Sequence" menu item the user can select "X-box entry" or "X-box entry away".

In discussing aerobatic sequences, "X" typically refers to the right-left axis of the box as viewed by the judges. But it's used here as an abbreviation for the word "cross". And cross-box entries take place on the Y axis.

I recommend changing these menu items to "Y-axis entry" and "Y-axis entry away".

**Comment by OpenAero** [comment]
Good point. But maybe it's best to just change it to Crossbox? This would
be clear for anybody.

Op wo 2 okt. 2019 om 17:05 schreef DJ Molny <notifications@github.com>:

**Comment by djmolny** [comment]
The meaning of "Cross-box entry" is clear and that change would eliminate any confusion.

**Comment by OpenAero** [comment]
Great! Will be in the next version.

Op do 3 okt. 2019 15:57 schreef DJ Molny <notifications@github.com>:
