### ISSUE TITLE
IAC Advanced free family 2 requirement 

### ISSUE THREAD

**Issue by davessn763** [OpenAero/main#246]
The rule checker allows competition turns(2.1.1 2.2.1 2.3.1 and 2.4.1) to satisfy  the rolling  requirement. 

23.4.1.3 At least one Rolling Turn (2.1.2 thru 2.1.3, or 2.2.2 thru 2.2.7, or 2.3.2 thru 2.3.6, or 2.4.2 thru 2.4.8)

**Comment by OpenAero** [comment]
Fixed in 2021.1.7
