### ISSUE TITLE
IAC Glider sequences are printed on CIVA forms

### ISSUE THREAD

**Issue by djmolny** [OpenAero/main#247]
**To reproduce:**
1. Create a new sequence with class=Glider, rules=IAC, category=(any), program=(any)
2. Insert a figure
3. Select File -> Print/Save Forms
4. Select Print/Save PDF
5. Note that the right-hand column matches CIVA forms (`Harm.`, `Penalties`, etc.)

**Diagnosis:**
- `js/main.js`, line 7814: `iacForms = (ruleName === 'iac') ? true : false;`
- I inserted `alert(ruleName)` at that point and it displayed `glider-iac`, therefore `iacForms` was set to `false`
- The exact same problem is present in `js/rulesWorker.js`, line 644

**SOLUTION:** In both files, change the ternary test to:
`iacForms = (ruleName === 'iac' || ruleName === 'glider-iac') ? true : false;`

**Comment by djmolny** [comment]
The info above refers to version 2021.1.9.

**Comment by djmolny** [comment]
Update: the user can work around this problem by selecting the option `A/B/C forms in IAC style` on the print dialog.

**Comment by djmolny** [comment]
Probably related: Form A for IAC Glider sequences does not display the word "Glider" anywhere, leading to confusion with Power sequences.

Attachment 1: The top of a CIVA Form A Glider sequence.
![Screenshot from 2021-08-16 08-57-22](https://user-images.githubusercontent.com/835079/129584750-1e6e5264-222d-4580-8311-be54d8b50e1d.png)

Attachment 2: The top of an IAC Form A Glider sequence.
![Screenshot from 2021-08-16 09-00-21](https://user-images.githubusercontent.com/835079/129584870-84345869-c4b0-4bcd-a301-b3b2e9e78ff8.png)

**Comment by OpenAero** [comment]
Thanks for the information. I will look into it in September.

Op ma 16 aug. 2021 om 17:00 schreef DJ Molny ***@***.***>:

**Comment by bdkjones** [comment]
This just tripped up a competitor heading to The Tequila Cup. It seems that the "A/B/C Forms in IAC Style" print option is automatically enabled for Power but **not** automatically enabled for Glider, even though in both cases the "rules" category is set to IAC.

**Comment by OpenAero** [comment]
Hi Brian,

Thanks for the info. I'll correct this. Update will probably be done
sometime after the CIVA meeting, so I can also incorporate rule changes and
new sequences from that.

Best regards,
Ringo

Op wo 10 nov. 2021 om 17:51 schreef Bryan Jones ***@***.***>:

**Comment by djmolny** [comment]
Yes, I think that's a very good approach that eliminates any possible confusion.

**Comment by OpenAero** [comment]
Great! I'll update it like this.

**Comment by OpenAero** [comment]
Power or Glider added to forms from 2022.1.7.
