### ISSUE TITLE
Annotate Cross-Box Entries

### ISSUE THREAD

**Issue by djmolny** [OpenAero/main#248]
IAC Rule 21.3.4 states:
> The notation, "Note Y Axis Entry", or "Note Downwind Entry" shall appear on Forms B and C if the
sequence does not begin upwind.

Competitors sometimes forget to add that notation manually, and it would be very helpful if OpenAero could do that automatically.

**Comment by OpenAero** [comment]
Is there any guidance in the rules on where this should appear? Right on
the top of the page or within the sequence area? Special font color or just
black?

Op wo 29 sep. 2021 om 16:05 schreef DJ Molny ***@***.***>:

**Comment by djmolny** [comment]
Hello, Ringo.

The IAC Rule Book only says:
> 21.3.4 The notation, "Note Y Axis Entry", or "Note Downwind Entry" shall appear on Forms B and C if the
sequence does not begin upwind.

I've seen that notation appear in both places. In my opinion, it's more obvious if it appears within the sequence area. For example, IAC's 2021 Glider Advanced Known has the notation at the top of the B/C forms, and I know that some judges did not notice it:
[ADVP-Known-2021.pdf](https://github.com/OpenAero/main/files/7533843/ADVP-Known-2021.pdf)

**Comment by OpenAero** [comment]
How about this example?

Op zo 14 nov. 2021 om 14:52 schreef DJ Molny ***@***.***>:

**Comment by djmolny** [comment]
I like it! But let me ask a few IAC leaders what they think, and I'll give you a final answer in a day or two.

**Comment by djmolny** [comment]
The people that I polled all approve of your example. Thank you for implementing this feature!

**Comment by OpenAero** [comment]
Great! I'll apply the update together with CIVA Free Known sequences and new rules (if any) for 2022. Likely about halfway december.

**Comment by OpenAero** [comment]
Fixed in 2022.1.4

**Comment by djmolny** [comment]
Thank you, Ringo!
