### ISSUE TITLE
Language Support

### ISSUE THREAD

**Issue by Dirk07** [OpenAero/main#250]
Hi @OpenAero,

Today I've received another request, whether there is some Manual / Guide / Tutorial available in German Language in order to implement this to the training for aerobatic instructors, eventually to further harmonize aerobatic education in Germany.

Although, it is not a too huge task to translate the available help files 'Manual', 'OpenAero language' and 'Aresti System' into German, I would not want to update these translated files manually, whenever there's a new feature implemented that requires explanation.

Thus, I'd rather like to know whether some automated, reliable translation (i.e. sth. like google translate services or similar) could be implemented, which then requires always only a review by a native speaker, who could be enabled to correct it accordingly, if necessary. I know that some translation fails must be expected, just when I think of the 'tailslide'.

If not seen feasible, I'd like to discuss other possibilities to improve language support, i.e. an aerobatics dictionary for at least French and German. 

Then, this could perhaps not just be applied on the support files, but also the entire GUI-commands, for several languages.

Best regards,
Dirk

**Comment by Dirk07** [comment]
Hi Ringo,
having reviewed my aresti_system_de.html, I discovered a new issue on the German "ä", "ö", "ü" and possibly also "ß" ... for all of them exist alternatives: "ae", "oe", "ue" and "ss", but it doesn't look so natural. I'm sure you know, how to overcome this in html.[
![Screenshot 2023-02-09 235152](https://user-images.githubusercontent.com/86533172/217957496-743e52f9-57b3-4246-90ea-a3af7879800e.png)
](url)

**Comment by Dirk07** [comment]
Great!
Having reviewed it on my mobile, the page appears as expected, now.

**Comment by OpenAero** [comment]
German language support is complete in 2023.3.7
