### ISSUE TITLE
Change IAC Presentation K for 2023

### ISSUE THREAD

**Issue by djmolny** [OpenAero/main#251]
Starting in 2023, the Presentation K factor for IAC Power Intermediate sequences will be 20K and Power Advanced sequences will be 30K.

**Comment by OpenAero** [comment]
Hi,

Thanks, will update on the next version in a few weeks. Can you send me the
Known sequences when they are published?

Best regards,
Ringo

Op di 15 nov. 2022 om 14:55 schreef DJ Molny ***@***.***>:

**Comment by djmolny** [comment]
Note that these changes only apply to Power sequences. The Presentation K factors for Glider sequences remain unchanged.

**Comment by djmolny** [comment]
I put links to all ten sequences in issue #253.

**Comment by OpenAero** [comment]
Merged with issue #253
