### ISSUE TITLE
Glider Primary category (IAC)

### ISSUE THREAD

**Issue by djmolny** [OpenAero/main#252]
The IAC Board voted to create a new Glider Primary category starting in 2023. Please add this option to OpenAero.

I will send the Known sequence, including Presentation K, early next week.

**Comment by OpenAero** [comment]
If specific sequence rules for Unknowns etc need to be added, this should preferably be done from within IAC. If just the Known is required, this issue can be merged with #253

**Comment by OpenAero** [comment]
As Glider Primary Known K is 0, and no rules are required, forms can be created by typing "Primary" in the Category field. Closing issue.
