### ISSUE TITLE
Add IAC 2023 Known Sequences

### ISSUE THREAD

**Issue by djmolny** [OpenAero/main#253]
Glider Primary (note the dependency on issue #252): https://openaero.net/?s=hFByaW1hcnmHZ2xpZGVyiEtub3duiUlBQ43-aWQuq34gKDIsMCkgq29qq6v-IDYlIGArM2orYCAnMX4gYCsuaneuri4rYCAtMSUgb49JQUOQMjAyMi4yLjWRQg

Glider Sportsman: https://openaero.net/?s=hFNwb3J0c21hbodnbGlkZXKIS25vd26JSUFDijE1izCNZCcg_ml2JzZzri4rIG8gMnJkYq4u_iAuYy4sMq6uLid-IDMlIODgK29q_iB-aqsrfiAnMf6PSUFDkDIwMjIuMi41kUI

Glider Intermediate: https://openaero.net/?s=hEludGVybWVkaWF0ZYdnbGlkZXKIS25vd26JSUFDijE1izCNc2lycKcy_iAyLSAxNCUgLWEg4HJ5IP4nMqd0Lic0Lif-ICsnaCw0LicrfiAxMCUgYCvg4OBgMmByYyvg4GAgKDEsMCkgLTIlIP6rKycyLnJkYq6urq6uK-Dg4CA2JSBtLDKPSUFDkDIwMjIuMi41kUI

Glider Advanced: https://openaero.net/?s=hEFkdmFuY2Vkh2dsaWRlcohLbm93bolJQUOKMjWLMI00OC0gLXSurq6nIFstMTIsMF0gK3JwKDI0KSv-ICgtMiwwKSCndGGupyvg4GAgfiwycmRiLn4gri6ncCgyKa6nfiBvMjQsMiB-qydoNC4g4GAr4HBiLDQnK-AgtJAyMDIyLjIuNZFC

Glider Unlimited: https://openaero.net/?s=hFVubGltaXRlZIdnbGlkZXKIS25vd26JSUFDijI1izCNaWSnMjSnLSAtMnJjLSAoLTcsMTIpIC0yYzJpZi4gMjQtIC2ndGE0Licr4CBirjNpZiA0JSBvMjQsMiAvpzQuaCt-IDFqbzGPSUFDkDIwMjIuMi41kUI

Power Primary: https://openaero.net/?s=hFByaW1hcnmGMjAyM4dwb3dlcmVkiEtub3duiUlBQ4o1izCNZCBpdmA2c66nIC5jLicyYCvgICgtMTUsMTMpIG8gNSUgMmorIDGPSUFDkDIwMjIuMi41kUI

Power Sportsman: https://openaero.net/?s=hFNwb3J0c21hboYyMDIzh3Bvd2VyZWSIS25vd26JSUFDijEwizCNbyBkaCjgKa6nq6ur_iAoLTIsMCkgK2uurqcyNK6nIGBtMiBgMX4gKC00LDApIDUlIP4yaiAoLTIsMTApIGQg_itpdjVzJyBiLic0IK5jLjIuJ49JQUOQMjAyMi4yLjWRQg

Power Intermediate: https://openaero.net/?s=hEludGVybWVkaWF0ZYdwb3dlcmVkiEtub3duiUlBQ4oxNYswjEludGVybWVkaWF0ZSBLbm93bo1xbyDgK3YuNF4gaXbgNnOuri4nIGIuJzQgMSUgfqcycmMrYCAoLTQssikgYCtvZiA0JSDgbbItICgtOCwwKSCyJSAtMmot4OAgLTI0IDIlIODg4ODg4GAyaWFjKOAyKSvg4GAgZGiuLicgKC0yNiwwKSB-p2uuMjQuj0lBQ5AyMDIyLjIuNZFC

Power Advanced: https://openaero.net/?s=hEFkdmFuY2VkhjIwMjOHcG93ZXJlZIhLbm93bolJQUOKMjWNMjRkaCgnKS4nMmYuK34gL_6rq66ubigsNDguKacsMjSnrSAoMTMsMCkgLTVpc66urq6uJ2liLDgtICgtMiwwKSAtaWRxLSAxNSUgLeBhLDYtICg3LDApIC0zLmKurjMupyvgYCA0JSBvsiAoLTYsMCkg_mAyp2uuri6nsq6nICg1LDApIOBtpzMyJzs2Zi1-ICgtMTIsMCkgLTNqMy0-j0lBQ5AyMDIyLjIuNZFC

Power Unlimited: https://openaero.net/?s=hFVubGltaXRlZIYyMDIzh3Bvd2VyZWSIS25vd26JSUFDijQwizCNMmlmcnAotCknMy6nLDj-IC4sOHRhM2auLqcgKDIsMCkgLzMucOIoLiw1Zq4pLiw0pywyp34g4GA1czsyaWauLmlycCcyNC6nLDEr4OAgL-ArM2oxNS0grXBiLqc1riCrq6szaWYnaC4nMy6nIODgsmFjKDZpZuApJzinLDUt4ODgIDglIC3gYGlmYTEsOf6PSUFDkDIwMjIuMi41kUI

**Comment by OpenAero** [comment]
Thanks. When adding these, two things seemed incorrect:
- Presentation K for Power Advanced Known is set to 25. Should this not be 30?
- Presentation K for Glider Primary is not set. What should the value be?

**Comment by djmolny** [comment]
You're right, those sequences were produced before the IAC Board approved an increase to the Presentation K-factors for the Power categories. I will get you new sequence files as soon as I can. Just for your reference, the new values are:
![Screenshot from 2022-12-06 17-45-49](https://user-images.githubusercontent.com/835079/206059919-66b02537-c42f-404e-af82-0a72702778a3.png)


The Presentation K for Glider Primary is 5.

**Comment by djmolny** [comment]
Here are .seq files for all five Power categories with the correct Presentation K-factors. (The Presentation K-factor for IAC Glider categories is unchanged.)
[IAC 2023 Power Knowns.zip](https://github.com/OpenAero/main/files/10172220/IAC.2023.Power.Knowns.zip)

**Comment by OpenAero** [comment]
Thanks. Sure about the (high) K factors for Power? Issue #251 gives different values.

**Comment by djmolny** [comment]
You're absolutely right, sorry about that! The numbers are above were from the original rule change proposal. The numbers below are what the IAC Board of Directors actually approved:
![Screenshot from 2022-12-08 12-22-23](https://user-images.githubusercontent.com/835079/206548607-e7f763c7-8690-4fe0-90ae-f155b5e5f0ad.png)

**Comment by OpenAero** [comment]
All sequences have been added. Please check at https://openaero.net/devel

**Comment by OpenAero** [comment]
Sequences are added and checked in 2023.1.3.
