### ISSUE TITLE
Add IAC R-L forms

### ISSUE THREAD

**Issue by djmolny** [OpenAero/main#254]
I've attached both the Visio originals and PDF renderings. Let me know if you need anything else.

[IAC-RL-Forms.zip](https://github.com/OpenAero/main/files/10149886/IAC-RL-Forms.zip)

**Comment by OpenAero** [comment]
Work almost complete. Two questions:
- Is the "Harmony" grade ever used by IAC? For example for Glider
- After "Category:", would you like "Power Unlimited", "Glider Intermediate" etc, or just "Unlimited", "Intermediate" etc.

**Comment by OpenAero** [comment]
The forms have been added. Please check at https://openaero.net/devel

**Comment by OpenAero** [comment]
Forms are added and checked in 2023.1.3.
