### ISSUE TITLE
IMAC Rules/templates 

### ISSUE THREAD

**Issue by Bdavy92960** [OpenAero/main#255]
New IMAC sequence committee chair here. Looking for assistance getting IMAC into openaero. Unfortunately I’m not a coder. Anyone interested?

**Comment by OpenAero** [comment]
Great to see that IMAC may be adding rules too. To get started, have a look at https://github.com/OpenAero/main/wiki/Developers#creating-rule-checking-files

**Comment by Bdavy92960** [comment]
Thank you.  I guess, if I understand the process, I need to take one of the existing rule files, and edit it to cover the IMAC unknown rules, which will be our primary use.   Basic process is to only allow certain figures based on class, which I believe can be included in a single rules file, but it may get pretty big.  The rule files I'm looking at all pretty much allow all figures.  Will have to find one that is restricting figure choices.  Not sure I have the requisite understanding of the Regex, but will give it a shot.

**Comment by OpenAero** [comment]
Hi, this is the approximate process. Would be best to let a coder do it though, as it will be much easier for them. I assume there must be many at IMAC. A rule file can be as big as needed, there is no limit. Do make sure that there are sufficient comments (line starting with //) to make future updates easier.

For reference, the file js/rules/rules23-civa.js contains a wide range of rule codings, including only allowing specific figures with limitations on the rolls. For example, under "(CIVA Advanced Unknownbase)":
"allow-defrules= Hor10stop",

"1.1.1.1-4",
"1.1.2.1-4 NOU",
"1.1.3.1-4 NOU",
"1.1.6.1-3 NOU ; NRLevFly",
"1.1.6.4   NOU ; NRPushout",
"1.1.7.1-2 NOU ; NRLevFly",

etc...

**Comment by Bdavy92960** [comment]
Thank you.  I'm working my way through the allowed unknown figures for IMAC, but have noticed a strange behavior related to Snap/Flick roll selection on up and down lines.  In all other cases (horizontal, 45) the program correctly limits snap roll selection according to the rule file I have selected, but in the case of the up and down lines, the program allows me to select a snap that is not allowed by the rule file, then gives me an alert that the snap element is not allowed.

For example, I have the following specific lines added to my rule file: 
//9.9 Positive Flick Rolls 
"allow=^9.9.1\\.[2-4]",
"allow=^9.9.2\\.[2|4|6]",
"allow=^9.9.3\\.[2|4|6]",
"allow=^9.9.4\\.[2|4|6]",
"allow=^9.9.6\\.[2-4]",
"allow=^9.9.7\\.[2|4|6]",
"allow=^9.9.8\\.[2|4|6]",
"allow=^9.9.9\\.[2|4|6]",
"allow=^9.9.5\\.[2-6]",
"allow=^9.9.10\\.[2-6]",

Despite these defined allowed maneuvers, the program allows me to select 9.9.1.5, 9.9.1.6, 9.9.6.5, and 9.9.6.6.  

What am I missing, or is there a bug in the program regarding uplines character (positive vs. negative line)?

 BTW, I did have a more condensed version of the rules, but spelled them out more specifically to ensure I wan't making a regex error.

Thanks,
Brad

**Comment by OpenAero** [comment]
Hi,

First, regarding bugs; as in any piece of software, OpenAero can contain bugs. However, the rule checking algorithm doesn't change often and has been extensively tested on many rules for more than 10 years. Therefore, it is unlikely to contain bugs.

For the allow regex, according to the post above, you have used for example "allow=^9.9.1\\.[2-4]". This would match first a 9, then any character (the dot, see https://www.regular-expressions.info/dot.html), etc. So this would not match as it should.

Adding a list of approved figures is best done without the use of regex, using just "9.9.1.2-4", as in the example below from rules23-civa.js:

> "1.1.2.1",
"1.1.2.2",
"1.1.2.3-4",
"1.1.3.1",
"1.1.3.2",
"1.1.3.3-4",
"1.1.6.1-4",
"1.1.7.1-4",

Although using regex might make it possible to keep the rules more compact, it would make them much harder to maintain. A simple list of figures is easy to update and checked against a rulebook. As mentioned before, the size of rule files is not an issue.

**Comment by Bdavy92960** [comment]
Thank you. Will work from that direction. Appreciate your patience.

**Comment by Bdavy92960** [comment]
Well, I tried it without using the regex expressions and allow statements, but I'm still getting the same behavior.
For example, in the rules file I have the following for positive flick rolls: 
"9.9.1.2",
"9.9.1.3",
"9.9.1.4",
"9.9.2.2",
"9.9.2.4",
"9.9.2.6",
"9.9.3.2",
"9.9.3.4",
"9.9.3.6",
"9.9.4.2",
"9.9.4.4",
"9.9.4.6",
"9.9.5.2",
"9.9.5.3",
"9.9.5.4",
"9.9.5.5",
"9.9.5.6",
"9.9.6.2",
"9.9.6.3",
"9.9.6.4",
"9.9.7.2",
"9.9.7.4",
"9.9.7.6",
"9.9.8.2",
"9.9.8.4",
"9.9.8.6",
"9.9.9.2",
"9.9.9.4",
"9.9.9.6",
"9.9.10.2",
"9.9.10.3",
"9.9.10.4",
"9.9.10.5",
"9.9.10.6",

When I enter a figure with a vertical up line, the graphic interface allows me to select 9.9.1.5, 9.9.1.6, 9.10.6.5 or 9.10.6.6, and then tells me in the warnings that it's not permitted in the sequence.  

Its working properly for all the other rolls, just not for the flick rolls.

**Comment by OpenAero** [comment]
Thanks for the detailed report. So the rule checking is working as it should, but some flick rolls that should not show up in the selection list, actually do? I'll check to see if I can reproduce this.

**Comment by Bdavy92960** [comment]
If needed, I can send you my rules file that I'm loading.  There are no other functions included other than defining allowed figures.

Thanks

**Comment by OpenAero** [comment]
Probably no need, I've made an update that should fix this. Try loading your rules on https://openaero.net/devel (may need to reload twice to make sure you have the update).

**Comment by Bdavy92960** [comment]
That fixed it.  Thanks for the very quick response.  Clearly someone that knows what they're doing knows where to look!

Now on to drafting total rotation rules (if I can figure that out).  Tomorrow.  Should I continue to use the devel version for now, or do you expect to push out a new version soon?

Thanks!

**Comment by OpenAero** [comment]
That great! I've pushed this update to openaero.net, the app versions are not yet updated but I'll wait with that until we you have the IMAC rules complete (or at least at a level at which you'd like to publish them). Are there also IMAC known sequences and/or figure sets for Free Knowns?

**Comment by OpenAero** [comment]
Just checked the IMAC site and I see that you indeed have Known sequences. Also glad that nobody has to be in the airplane when flying your Unlimited sequence!
If you want the Known sequences added to the OpenAero library, could you supply them as sequence links?

**Comment by Bdavy92960** [comment]
I think the complexity and content of the IMAC sequences has been one if the biggest hurdles we have faced in producing sequences. Our old program, the Aresti add—on for Visio, would cause errors during sequence construction because of all the inapplicable rules. You can do a lot with a plane that has a 2+ power to weight ratio😊

I assume the known sequence is provided in an appropriatly labeled section of the rules file, aling with the sequence string built by the software?  If so I will definitely include it.

I’m at the 90 percent confidence level now, and should have it ready to go next week.

Brad

Sent from my iPhone

On Jan 13, 2023, at 3:24 AM, OpenAero ***@***.***> wrote:

﻿

Just checked the IMAC site and I see that you indeed have Known sequences. Also glad that nobody has to be in the airplane when flying your Unlimited sequence!
If you want the Known sequences added to the OpenAero library, could you supply them as sequence links?

**Comment by OpenAero** [comment]
Known sequences are added in this file: js/library.js. This allows keeping sequences in the library over the years. As you can see in the file, they are included as sequence links. These can be created in OpenAero from _File -> Save as iink_. You can open a separate issue, containing the links, and I will add them to library.js.

**Comment by Bdavy92960** [comment]
Another stupid question that I hope is simple for you.  I'm trying to include a rule for Sportman 5.3.1.1 and 5.3.2.4 that prohibits point(hesitation) rolls.  I'm including the FAM91 as follows (MAX180 was a rule I created in my file based  on MAX360 from the rules23.js):
"5.3.1.1 MAX180; FAM91",
"5.3.2.4 MAX180; FAM91",

The MAX180 properly alerts when a roll is greater than 180 degrees, but no matter what I do, the alert "only family 1 roll allowed" always shows up, even when there are no rolls added to the family 5 figures.

What am I doing wrong?

**Comment by OpenAero** [comment]
Great! And while you are working on these rule files, I would like to point out that it can be useful to put references to the official rule book in them. This is done using directive xxx-rule, where xxx is the OpenAero rule you are referencing. For example:
NOPOINT-rule = IMAC Sporting code, Part 2.3.4.1

These rules show when you hover over an Alert and are useful for confirming that the Alerts are valid. They have certainly not been implemented for all rule files yet, but starting from scratch might be a good time to do so.

If you want to see an example. try an empty sequence with rules "Power CIVA Advanced Programme2", then hover over "At least 1 additional figure required".

**Comment by Bdavy92960** [comment]
Yup, already doing it.  We don’t have a lot of notes in the catalog, but what is there is often hard to translate to rule for OpenAero.  Sportsman is the most restrictive, but I think I have that one done.  Moving on to Intermediate.

Brad

**Comment by Bdavy92960** [comment]
I'm 95 percent there but I'm looking for a solution to a sticky condition related to Family 5.3 and 5.4. IMAC makes some pretty complex limitations that a person can figure out, just trying to figure out how to script it.  Any help would be appreciated.  

For Intermediate 5.3.x.x-5.4.x.x:
Point rolls, if used, may not exceed 180 degrees, must be two points or less; may only be used on the vertical up-line or vertical downline.

For Advanced 5.3.x.x - 5.4.x.x.:
Uplines - Point rolls, if used, may not exceed 180 degrees of rotation; may only be on one of the two ascending lines (45 or vertical).
Downlines- Point rolls, if used, may not exceed 180 degrees of rotation; may only be on one of the two descending lines (45 or vertical).

I've stared at the civa rules and the answer may be in their structure of total stops and total quarters, but I'm not smart enough on scripting to understand exactly what their construct is, or how I can modify it to match what we need.

Thanks

**Comment by OpenAero** [comment]
In both cases you can use the "roll" conversion and NOPOINT rule that you used earlier. Apply this to specific figures and roll elements. To disallow point roll on 45 up line in hammerhead:
5.3.1.1 NOPOINT:1

For considering combinations, take a look at rule-NF3TOPH in rules23-civa.js which uses a similar construct to not allow flick rolls on vertical down after a hesitation roll in a loop.

**Comment by Bdavy92960** [comment]
The problem is constructing the determination that a point roll exists on one of the lines so it can be prohibited on the other line. In the advanced 5.3xx the point roll can be on position 1 or 2, and for 5.4xx it can be either 1 or 2 and either 3 or 4. 

In intermediate it must be limited to 2 points and less than 180 degrees, but can be combined with another roll for a total rotation limit of 540 up or 360 down. Essentially that means only 2x4 or 2x8 with another roll.

**Comment by Bdavy92960** [comment]
I figured out the point roll problem, but I'm still struggling with the maximum rolls on families 5.3 and 5.4.  The qtrs conversion is only totalling rolls on each leg of the maneuver.  IMAC has a rule for 5.3 and 5.4 that requires the total rotation on both the up legs and both the down legs.  How do I get the program to evaluate that condition (eg, 5.4.4.1, max 540 degrees of total rotation on legs 1 + 2 and then max 360 on legs 3 + 4.  

Thank you,

**Comment by Bdavy92960** [comment]
Yes flick rolls count. I’ll play with it today. What I was missing was the +<7, rather than <7. Thank you so much!

Brad

Sent from my iPhone

On Jan 16, 2023, at 3:24 AM, OpenAero ***@***.***> wrote:

﻿

This should work (adapted from CIVA Unlimited rules):

"conv-climbqtrs=^9\.([1-9]|10)\.[1267]\.([1-8]) = $2 ; ^9\.(9|10)\. = f ; ^9\. = r ; ^0\.=z",
"rule-twolineclimbmax540 = climbqtrs:+<7",
"why-twolineclimbmax540 = Maximum 540 degrees of rotation on legs 1 + 2",
"5.3.1.1 twolineclimbmax540",
...

I'm not sure if the use of flick rolls is applicable in your case or not. The above is only for counting normal rolls. If you want to incorporate flick rolls, you will have to adjust the conv to also count flick roll rotation quarters.

**Comment by Bdavy92960** [comment]
Doing my QA checks, I discovered that the conv-qtrs conversion in the rules23.js only counts rolls, not flick rolls.  Is this by design?

If so, I'll just revise in my rules file.  If not, I would recommend changing it to 
"conv-qtrs=^9\\.\\d+\\.\\d+.([1-8])=$1; ^0\\.=0", (added the + after the second d, which I guess gets double digits) in order to catch all the snap conditions.  It was reading the snaps correctly for negative snap on negative down line, and positive snap on positive downline, but then got confused with negative snap on a positive down, or positive snap on negative down.

**Comment by OpenAero** [comment]
Great find! I've checked it and no, this was not by design. It's a flaw in the conversion that never showed up in other rules because it wasn't applied in a way that would make this come up.
I'll change the conv-qtrs in rules23.js in a new release. In the meantime, you can revise it in your rules file.

**Comment by Bdavy92960** [comment]
Thanks.  I'm at the 99% confidence level with the rules file.  
Next task is to add IMAC Forms to the print options, if that is possible.   The top of form A and right side of Form A are pretty straightforward, but I think it means adding another condition in the main.js coding anywhere the if (iacForms) appears.    You've seen our known sequences.  I think for simplicity, the Top where the knowns state 2023 Known Scoresheet would be replaced with International Miniature Aerobatic Club and incorporate the Category and Program into the next line down.  I'm really not up to that task.  Can you help?

**Comment by OpenAero** [comment]
I've seen the "Call sheets". Those look rather straightforward and I could quickly add them. The descriptive text lines (such as "Pull to 45 upline, 1 full roll, ...") are a bigger issue. To have this fully automated would require quite some coding and testing. Alternatively, with limited coding I could add a possibility to add these to the Figure comments:

![image](https://user-images.githubusercontent.com/11457953/213742409-aa9567b1-82a0-44e5-bbe2-7ad83649e1cc.png)

Do you only use the call sheets? And are they always in the same landscape format?

**Comment by Bdavy92960** [comment]
Don’t want the remarks.  Attached is the type of form members are used to seeing.  We do not need the figure names or flight instructions in the remarks box.  That was added  in on the forms this year for convenience, and we could add it later with a PDF editor if people insist, but for unknowns, its blank.  Its intended to contain written remarks from the judge, but its never been used since I joined IMAC 15 years ago.

I don’t need the program to tell the pilot how to fly.

Brad

**Comment by OpenAero** [comment]
I don't see an attached form. Sure you sent it?

**Comment by Bdavy92960** [comment]
[2023 Advanced Alternate.pdf](https://github.com/OpenAero/main/files/10468010/2023.Advanced.Alternate.pdf)
I had sent via email, but looks like it didn't come through in the comment here.  I dragged and dropped it here.  Can you see it?
If not try [https://mini-iac.org/downloads/sequences/2023-knowns/download?path=2023%2BAdvanced.pdf](url)
Brad

**Comment by OpenAero** [comment]
Yes, that worked fine. I'll be looking into adding these, but that will be some work. Is it expected that this form layout will be around for a while? As both CIVA and IAC have now switched to L&R forms.

**Comment by Bdavy92960** [comment]
There is no reason to suspect that these forms will change as long as I’m the sequence committee chair (this is one of those positions nobody leaves until their dead, and I’ve hopefully got a couple of years left). 😊

**Comment by OpenAero** [comment]
I'm using IAC forms as the basis for IMAC forms. Regarding this, a few questions:
- Do the IMAC forms have a note when a sequence does not start upwind?
- Is there a reason why the _Catalogue No._ box on Form A is so wide? This is never necessary for the catalogue numbers, and uses space that could otherwise be used by _Symbol_ or _Remarks_.
- Does the _A/C Type_ only contain type? Do you have/use a registration?

**Comment by Bdavy92960** [comment]
See answers below.

Thanks again for your help!

Sent from my iPhone

On Jan 21, 2023, at 7:25 AM, OpenAero ***@***.***> wrote:

﻿

I'm using IAC forms as the basis for IMAC forms. Regarding this, a few questions:

  *   Do the IMAC forms have a note when a sequence does not start upwind?

No.

  *   Is there a reason why the Catalogue No. box on Form A is so wide? This is never necessary for the catalogue numbers, and uses space that could otherwise be used by Symbol or Remarks.

No reason.

  *   Does the A/C Type only contain type? Do you have/use a registration?

These are only used if form A is used by the judges to record scores and I’ve never seen them used. We have an IMAC number but no need for it on these forms.

**Comment by OpenAero** [comment]
Another question:
Is the margin on the right of the sequence in Form B and C used? If not, I can increase the sequence area width.

**Comment by Bdavy92960** [comment]
No, the margin is unused. I think it’s probably just there because people believe there should always be a 1/2 inch margin.


Sent from my iPhone

On Jan 21, 2023, at 8:07 AM, OpenAero ***@***.***> wrote:

﻿

Another question:
Is the margin on the right of the sequence in Form B and C used? If not, I can increase the sequence area width.

**Comment by Bdavy92960** [comment]
[rules23-imac.txt](https://github.com/OpenAero/main/files/10475276/rules23-imac.txt)
This is the IMAC rules file for 2023.  I've checked it 6 ways from Sunday, and I think I have it right.  I had to change the extension from .js to .txt to upload it.  If I do discover anymore errors, what is the process to make corrections? 

Also, here are the sequence links for the 2023 IMAC Known Sequences for Basic through Unlimited:
2023 IMAC Basic Known Sequence:  https://openaero.net/?s=hEJhc2ljhjIwMjOHcG93ZXJlZIhLbm93bolJTUFDjTEgMnQgKDAssSkgYiAoLTMsMCkgMnJkYiBbLTMsOV0gbyAoMiwwKSBori4nICgtOCwxKSCup3muLiwyLicgY66uJywyYCAoLTMsMSkgbTIgKDE4LDApIGl2NnOuJ5AyMDIzLjIuMZFC

2023 IMAC Sportsman Known Sequence: https://openaero.net/?s=hFNwb3J0c21hbodwb3dlcmVkiEtub3duiUlNQUOMMjAyMyBJTUFDIFNwb3J0c21hbiBLbm93bo0xeSAoMywwKSBmbSwyNCAoLTI2LC0zKSBpdjI0rq4uICgxMywyKSAycmMxIFs2LDE2XSBvMSBoOCD-pzGuJ2JgM66upyAoMiwwKSBkZiAoNCwwKSBpdjZzrq4gKC00LDApILJhYygyNCktkDIwMjMuMi4xkUI

2023 IMAC Intermediate Known Sequence:  https://openaero.net/?s=hEludGVybWVkaWF0ZYdwb3dlcmVkiEtub3duiUlNQUONLWlmaWFjMjQsMi0gLS4stC6naK4uLSAoLTIsMCkg_i1vsi0gfq0zcGIyNC4nIP40LmuuNqcgeicsNCw4LiAoNCwwKSBpdjdzLDOuri4tIK0tLiczMi56dK4uJ6t-ICgtMiwwKSBmYy4nNDgupyAxajGQMjAyMy4yLjGRQg

2023 IMAC Intermediate Known Alternate Sequence  https://openaero.net/?s=hEludGVybWVkaWF0ZYdwb3dlcmVkiEtub3duiUlNQUONLWlmaWFjMjQsMi0gLS4stC6naK4uLSAoLTIsMCkg_i1vsi0gfq0zcGIyNC4nIP40LmuuNqcgeicsNCw4LiAoNCwwKSBpdjdzLDOuri4tIK0tLiczMi56dK4uJ6t-ICgtMiwwKSBmYy4nNDgupyAoOSwwKSBhbywykDIwMjMuMi4xkUI

2023 IMAC Advanced Known Sequence:  https://openaero.net/?s=hEFkdmFuY2Vkh3Bvd2VyZWSIS25vd26JSU1BQ400OHJxNmlmILJwNSAoLTEsMSkg_qsrM2ozqyt-ICgyLDEpICwzZiw4aDGuri0gMiUgLW-0LSAoLTQsMCkgL_6trS6nMmYsMjQuJ3p0rq4uJzNpZi0gKDAsMikgMSUgLac0OKdCYiiuLic1ZicpLqcxpy0-ICixLDApIK1pduDgNmlzLDI0rq6uJyAoLbEsMSkgLGY7MnJjuCv-ICgwLDE4KSBy8DYr_pAyMDIzLjIuMZFC

2023 IMAC Advanced Known Alternate Sequence: https://openaero.net/?s=hEFkdmFuY2Vkh3Bvd2VyZWSIS25vd26JSU1BQ400OHJxNmlmILJwNSAoLTQsMykgfiwzcGIsMjQgKDYsMCkgLDNmLDhoMa6uLSAyJSAtb7QtICgtNCwwKSAv_q2tLqcyZiwyNC4nenSuri4nM2lmLSAoMCw0KSAxJSAtLjQ4p0JiKK4uJzVmYCmuJzHgYC3gYD4gKDEzLDApIK1pduDgNmlzLDI0rq4gKC2xLDEpICxmOzJyY7gr_iAoMCwxOCkgcvA2K_6QMjAyMy4yLjGRQg

2023 IMAC Unlimited Known Sequence: https://openaero.net/?s=hFVubGltaXRlZIdwb3dlcmVkiEtub3duiUlNQUONLTRqMS0-ICgtMiwwKSAt4GAsN2lmLDR5ri6nMSctIC1vMzQsM2lmLSAtLjU0ridwYnBiKOBgOa6uricpLjVpZuCrIODgN3MnLDOuridpa3ouJywyYCwyNC7-ICgyLDApILElIOA2ZmE0OCwxLeAgKC0xLDQpIDQlIOAtYCy0YHJjNSw1Zivg4GAgKC01LDE1KSDg4ODgK2BpZiwy4HpiJ7It_iAtLDNpZiw4aKc2ri4nLSAtcnAoLDI0KSwyZiwykDIwMjMuMi4xkUI

2023 IMAC Unlimited Known Alternate Sequence: https://openaero.net/?s=hFVubGltaXRlZIdwb3dlcmVkiEtub3duiUlNQUONMzQsM2lhYygxKSw0OC0gKC0yLDApIC3gYCw3aWYsNHmuLqcxJy0gLW8zNCwzaWYtIC0nNTSncGJwQijgOa4uKS41aWZgqyDg4DdzJywzrq4naWt6LicsMmAsMjQu_iAoMiwwKSCxJSDgNmZhNDgsMS3gICgtMSw0KSA0JSDgLWAstGByYzUsNWYr4OBgICgtNSwxNSkg4ODg4CtgaWYsMuB6YieyLf4gLSwzaWYsOGinNq4uJy0gLXJwKCwyNCksMmYsMpAyMDIzLjIuMZFC


Thank you so much for your help.  I believe once these are posted/included, and the forms are updated, we'll be able to close this issue.

Brad

**Comment by OpenAero** [comment]
Thanks! I've added the forms A/B/C, rules and sequences to the development version at https://openaero.net/devel. You can check them all there.

I have some questions/comments:
- The Basic sequence gives Alerts for figures 4 and 10. Is this intentional?
- None of the sequences have a logo selected. I have set the forms to display the IMAC logo when no logo is selected. However, this means that the forms cannot be printed without a logo. If this is desired behaviour, it's fine. Otherwise, the IMAC logo should be added to the sequences.
- The forms show the value of the rules _Category_ field under _Category_. For the Adv and Unl Alternate sequences this gives the same _Category_, making them impossible to tell apart. Possible solutions
(1) Create additional Categories with associated programs in rules23-imac.js: Advanced_Alternate and Unlimited_Alternate
(2) Create additional Programs _Alternate Known_ and find the reference to Alternate in the top of the form, e.g.: 2023 Advanced Alternate Known scoresheet
(3) Similar to (2), but taking the first word of a multi-word Program and appending it to the _Category_ value.
(4) Append the value of the _Notes_ field to the _Category_ value, setting _Notes_ value to "Alternate". This is kind of a hack and disables other uses of the Notes field
- The _Date_ value in the Known programs (except Basic) is empty. This is the value that should be used to create a title like "2023 Known scoresheet". Otherwise it will be "Known scoresheet".

Regarding sending updates, there are several options. You can create a new Issue and add the .txt file there, mail them to openaero.devel@gmail.com as a .txt file or push them to GitHub. The last option is nicest (no file renaming, record on GitHub etc.) but may require some effort at understanding. You can take a look at:
https://docs.github.com/en/desktop/installing-and-configuring-github-desktop/overview/getting-started-with-github-desktop
https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/adding-and-cloning-repositories/cloning-a-repository-from-github-to-github-desktop
https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/working-with-your-remote-repository-on-github-or-github-enterprise/creating-an-issue-or-pull-request

**Comment by Bdavy92960** [comment]
Thank you.  I will create the Int Adv and Unl alternate categories today and check what I messed up in basic. I will also add the logo=“imac” to all categories   Then will try to do the update with the github desktop environment.


Sent from my iPhone

On Jan 23, 2023, at 4:13 AM, OpenAero ***@***.***> wrote:

﻿

Thanks! I've added the forms A/B/C, rules and sequences to the development version at https://openaero.net/devel. You can check them all there.

I have some questions/comments:

  *   The Basic sequence gives Alerts for figures 4 and 10. Is this intentional?
  *   None of the sequences have a logo selected. I have set the forms to display the IMAC logo when no logo is selected. However, this means that the forms cannot be printed without a logo. If this is desired behaviour, it's fine. Otherwise, the IMAC logo should be added to the sequences.
  *   The forms show the value of the rules Category field under Category. For the Adv and Unl Alternate sequences this gives the same Category, making them impossible to tell apart. Possible solutions
(1) Create additional Categories with associated programs in rules23-imac.js: Advanced_Alternate and Unlimited_Alternate
(2) Create additional Programs Alternate Known and find the reference to Alternate in the top of the form, e.g.: 2023 Advanced Alternate Known scoresheet
(3) Similar to (2), but taking the first word of a multi-word Program and appending it to the Category value.
(4) Append the value of the Notes field to the Category value, setting Notes value to "Alternate". This is kind of a hack and disables other uses of the Notes field
  *   The Date value in the Known programs (except Basic) is empty. This is the value that should be used to create a title like "2023 Known scoresheet". Otherwise it will be "Known scoresheet".

Regarding sending updates, there are several options. You can create a new Issue and add the .txt file there, mail them to ***@***.******@***.***> as a .txt file or push them to GitHub. The last option is nicest (no file renaming, record on GitHub etc.) but may require some effort at understanding. You can take a look at:
https://docs.github.com/en/desktop/installing-and-configuring-github-desktop/overview/getting-started-with-github-desktop
https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/adding-and-cloning-repositories/cloning-a-repository-from-github-to-github-desktop
https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/working-with-your-remote-repository-on-github-or-github-enterprise/creating-an-issue-or-pull-request

**Comment by OpenAero** [comment]
No need to add the "logo=imac". Best to just add the IMAC logo and year to each individual sequence before creating the sequence link. From now on, selecting IMAC rules will automatically add the logo for you.

![40C45BF0-8186-489A-B40B-2C10C3B35A4A](https://user-images.githubusercontent.com/11457953/214035399-f9b643ff-92c3-409d-b4fc-bc63fe413a6c.jpeg)

**Comment by Bdavy92960** [comment]
Understood!


Sent from my iPhone

On Jan 23, 2023, at 7:05 AM, OpenAero ***@***.***> wrote:

﻿

No need to add the "logo=imac". Best to just add the IMAC logo and year to each individual sequence before creating the sequence link. From now on, selecting IMAC rules will automatically add the logo for you.

[40C45BF0-8186-489A-B40B-2C10C3B35A4A]<https://user-images.githubusercontent.com/11457953/214035399-f9b643ff-92c3-409d-b4fc-bc63fe413a6c.jpeg>

**Comment by Bdavy92960** [comment]
Tried pushing a revision to rules23-imac.js today.  I think I did it right.  Let me know.  There were some errors in roll conversions in the rules file that I corrected.

**Comment by OpenAero** [comment]
Yes, that worked great! Have just uploaded the change to devel.

**Comment by OpenAero** [comment]
Completed in 2023.3.3
