### ISSUE TITLE
Revise Fam 0.1 X-axis image

### ISSUE THREAD

**Issue by djmolny** [OpenAero/main#256]
Here's a sequence drawing that includes 0.1 and 0.2 figures beginning on the X and Y axes:

![Screenshot from 2023-01-13 13-03-49](https://user-images.githubusercontent.com/835079/212410207-6e85dba2-7df5-4703-a787-ff9d453bc541.png)

The depiction of the X-axis 0.1 figure stands out because it's not so obvious that it's a loop. This has caused a little confusion on the judging line at IAC contests.

Could you make Figure 1 look like Figure 3, just move the 1/4 roll arrow to the appropriate position?

**Comment by OpenAero** [comment]
Not sure what the exact request is here. The 1/4 roll in figure 1 is in the correct position, being centered on the first half of the loop. After this, most of the loop is on the Y axis, which is why it's drawn in perspective. This is similar to a drawing of a full loop on the Y axis:
![Advanced Programme2  Form B_fig_1](https://user-images.githubusercontent.com/11457953/212432007-cef674c6-fe32-43c5-9809-b4eb1eb37fd1.png)

If you have a drawing of what you are looking for, I could see what is possible.

**Comment by djmolny** [comment]
Something like this:
![Family-0 1](https://user-images.githubusercontent.com/835079/212433042-0b88a3cb-e0b7-433a-8403-5833597111d1.png)

**Comment by OpenAero** [comment]
Ah, yes. But that's wrong. It shows the top of the loop going downwind, but it should be going crosswind. If you really want the "circular" shape of the loop, you could make the loop exit on crosswind away from the viewer. This is done using the button circled in red below:
![8B0C30FD-7E5D-46D9-8BF5-A4CA6090401E](https://user-images.githubusercontent.com/11457953/212433670-b2c47f41-d37f-461e-8110-a60c3356e157.jpeg)

**Comment by djmolny** [comment]
Background: I'm chair of the IAC Judges Program and teach judges school every year. Students are regularly confused by the default Fam 0.1 representation:
![Screenshot from 2023-01-13 13-01-37](https://user-images.githubusercontent.com/835079/212436481-45a470d1-84e0-4072-adf0-4b39be40cb39.png)
It makes perfect sense if you visualize flying it, but at a glance it doesn't look like a loop.

What I'm really looking for is a consistent representation of these figures as loops, where the line crosses over itself. I manually traced over the diagram you supplied in your latest response and just changed the exit line to show what I mean:
![20230113_160111-1](https://user-images.githubusercontent.com/835079/212435758-d2d502a3-ca37-4592-bf0e-49cc24c8fb43.jpg)

I hope this makes more sense, and thank you for all the work & quick responses.

**Comment by OpenAero** [comment]
To achieve this look, use "Flip Y-axis" on the figure (_Figure editor top middle button_) or the whole sequence (_Sequence -> Flip Y-axis_). The Y axis exit is then changed from running topright-bottomleft to topleft-bottomright. See the screenshot below. The Y axis can be flipped for each figure separately, but only after a change from X axis to Y axis, to prevent drawings with unnatural Y axis changes.
Interestingly of course, if a judge would see this figure flown (for example with smoke), the flightpath would never cross unless it was close to the upwind near edge of the box.

![6E45ACA6-825C-40BF-8AA2-5512FF25651B](https://user-images.githubusercontent.com/11457953/212462046-3124668b-5264-4f44-94c3-fc3517e0142f.jpeg)

**Comment by djmolny** [comment]
Thanks for the assistance, Ringo. I'm going to close this issue now that I understand the workaround. That said, I still think it would good if the default rendering looked more like a loop. :-)
