### ISSUE TITLE
Negative Flick Catalog mismatch

### ISSUE THREAD

**Issue by heyyouguesswho** [OpenAero/main#272]
Building a sequence and established a push hammer (5.2.1.4).  On the vertical downline I tried to use a negative 3/4 flick (9.10.10.3) which cataloged incorrectly as a (9.10.5.3).  

On a subsequent figure I used a double hump (8.8.6.1) and tried a negative 3/4 flick on the downline which should be negatively loaded and would therefore be (9.10.5.3) and that flagged the sequence as an illegal duplication.  

The humpty listed the correct Aresti catalog number for the negative snap but the hammerhead listed the wrong catalog number.

**Comment by djmolny** [comment]
The Aresti catalog and IAC rules both state that the AOA is zero following a stall turn (hammerhead), hence the lower K variant of the negative 3/4 flick (snap) is used. So OpenAero is doing the right thing.

![20230221_141004](https://user-images.githubusercontent.com/835079/220459775-fa78ab4b-2ffe-4ca6-9b20-4c7484b5ce5c.jpg)

**Comment by OpenAero** [comment]
Thank you DJ, I agree.

**Comment by heyyouguesswho** [comment]
The issue occurs on figure 5 and figure 7.  Can you clarify?  Shouldn’t Figure 5 be a 9.10.10.3 and 7 be a 9.10.5.3?

-Aaron

On Feb 21, 2023, at 3:18 PM, OpenAero ***@***.***> wrote:



Thank you DJ, I agree.

**Comment by djmolny** [comment]
I don't have access to your sequence, so I'll assume Fig 5 is the hammerhead and Fig 7 is the double humpty.

From the Aresti Catalog: "_In the case of vertical lines, after ... a stall turn ... any subsequent flick roll is accorded the lower of the two possible K-factors._"  The two choices for a negative 3/4 flick on a downline are 9.10.5.3 (13K) and 9.10.10.3 (15K). So the correct figure number is 9.10.5.3.

8.8.6.1 double humpty is a pull-push-pull maneuver, so the second vertical line is negatively loaded. A negative snap performed on a negatively loaded line also warrants the lower K catalog number, 9.10.5.3. The illegal duplication is an IAC (and perhaps CIVA?) rule against duplicating catalog numbers in a Free program and has nothing to do with the line loading.

If you'd like to discuss this further, I suggest we take things offline. You can reach me at: judgeschair@iac.org

**Comment by heyyouguesswho** [comment]
I had attached a pdf of the sequence to that email.

I thought that since the Hammerhead resets the zero lift axis the line would be positively loaded where the pull push pull hump in figure 7 of the concept was a negatively loaded line.

In my CIVA Free Known at WAC last year I had two negative ¾ flicks on vertical downline on two different figures; both of which were humpty variants.  Was attempting to lay out the same in an IAC formatted freestyle concept.  However 'the lower of two k factors' on a hammerhead invalidates my claim defaulting to the 9.10.5.3 regardless of the line.

Thanks for the insight, my apologies for the false report on the software!


Aaron McCartan

Northern Planes Aerosport, LLC.

***@***.***

712-346-8700 (Mobile)

515-924-3300

________________________________

**Comment by OpenAero** [comment]
Thanks for clearing things up. Closing the issue.
