### ISSUE TITLE
Saving figures seperately

### ISSUE THREAD

**Issue by Dirk07** [OpenAero/main#275]
Current OpenAero Manual describes that for the function "saving figures seperately" it is possible to specifiy the file-type in the settings.
Although there is such setting appearing, it seems to be inoperative. When saving figures seperately, using the particular function in the file-menu, they are saved as PNG by default, without providing the user the opportunity to interact and change the file type to SVG.

**Comment by rolfbartels** [comment]
Yes I have this issue as well and would prefer SVG's, We'd also like the ability to not include the figure number in the image

**Comment by OpenAero** [comment]
Fixed in 2023.3.5.
@rolfbartels : I will look at including an option to remove the figure number from the image.

**Comment by rolfbartels** [comment]
@OpenAero thank you, is there also the ability to thicken the pos and neg lines, I am working on a project for a handheld scoring device, and we import the svg's, the current default line thickness is not as thick as required, below is an example, we have been manually copying out the SVG's from the call sheets, this export of SVG's will save us a ton of time.
![image](https://github.com/OpenAero/main/assets/5420513/98ad5af2-a361-4a8b-8e58-4171715d4077)

**Comment by OpenAero** [comment]
You can use the Expert Settings to change any drawing style. Lines are
changed by the "pos" and "neg" style. I've changed the "pos" thickness to
3px in the example below. In the future, I plan to add a feature to save or
load these settings, but this is not available yet.

[image: image.png]

Op ma 15 mei 2023 om 10:46 schreef Rolf Balrtels ***@***.***>:

**Comment by OpenAero** [comment]
Please check https://openaero.net/devel and let me know if the update in Settings provides the correct functionality.

**Comment by rolfbartels** [comment]
Yes it looks good thanks

**Comment by OpenAero** [comment]
Feature added in 2023.3.7
