### ISSUE TITLE
Pull Request 279 not promulgating to the program

### ISSUE THREAD

**Issue by Bdavy92960** [OpenAero/main#280]
Pull request was incorporated 4 days ago, but the program on the website is still not showing the correct permitted snap in sportsman.  THe change permitted 9.9.4.4 in Sportsman Known for IMAC, but it is still generating an alert that 9.9.4.4 is not permitted.

Brad

**Comment by OpenAero** [comment]
I understand that it may be unclear why the pull request is not in the stable OpenAero release yet.
However, creating an OpenAero release requires several other code changes and creation and testing of builds for the various apps. Also, the OpenAero version must be consistent over these various platforms.
So, first I need the time to make these changes and do testing. Then, it takes around 24 hours for the Apple review process to approve the iOS release. Overall, it can take from days to months for any update to appear, depending on the severity of the issue.
Would it help if I postpone the pull request incorporation until shortly before finalising a release?

By the way, I have uploaded a release for this update just now (version 2023.3.16).

**Comment by Bdavy92960** [comment]
No need to delay, now that I understand what it means. Thanks for the update.

Brad

Sent from my iPhone

On Sep 16, 2023, at 5:42 AM, OpenAero ***@***.***> wrote:

﻿

I understand that it may be unclear why the pull request is not in the stable OpenAero release yet.
However, creating an OpenAero release requires several other code changes and creation and testing of builds for the various apps. Also, the OpenAero version must be consistent over these various platforms.
So, first I need the time to make these changes and do testing. Then, it takes around 24 hours for the Apple review process to approve the iOS release. Overall, it can take from days to months for any update to appear, depending on the severity of the issue.
Would it help if I postpone the pull request incorporation until shortly before finalising a release?

By the way, I have uploaded a release for this update just now (version 2023.3.16).
