### ISSUE TITLE
2024 IMAC Known sequences

### ISSUE THREAD

**Issue by Bdavy92960** [OpenAero/main#282]
Here are the approved 2024 Known Sequences for IMAC.

2024 Basic Known https://openaero.net/?s=hEJhc2ljhTIwMjQgS25vd26HcG93ZXJlZIhLbm93bolJTUFDjTEgNT4g4ODg4CtkYuBgMiA4PiAuMi4ndK6uri6nIDY-IG8gNz4gaK4uIDU-IHkgMj4gMnJjICgzLDIxKSBi4DKnIDglIDI-IG0yIDE2PiCraXY2c64uj0lNQUOQMjAyMy4zLjE2kUI

2024 Sportsman Known  https://openaero.net/?s=hFNwb3J0c21hboUyMDI0IEtub3duh3Bvd2VyZWSIS25vd26JSU1BQ40vpzJkYixmLicrIDMlILE-IC4nInwiMjQuJ3Suri6nK2AgryA4PiA0JSBgK29mK2AgNT4gsi5jLqcsMi4nICgtOCwxNCkgNCUgpyyybTIgMzE-IC9pduBgN3OuLqcr_iA0JSA0PiB-K6diYDgupyA5PiAxeeBgMq6nKyAyMT4gfiunMjSnaC6nMq6r_iA1PiB-K-BgcnAoMSkyNC2PSU1BQ5AyMDIzLjMuMTaRQg

2024 Intermediate Known  https://openaero.net/?s=hEludGVybWVkaWF0ZYUyMDI0IEtub3duh3Bvd2VyZWSIS25vd26JSU1BQ40zJSAtNmBnMjQgMml5MS0gMTQlIDQ-IC3gLGlmYTQ4LDIr4CAoMCwxNCkgLGlmemIupyyyIDc-ILRoLjKuJy0gOD4gLW8yNCA2PiAvLDhwYixmri4t4CAyJSA0PiAtdjUgaXbgYDdzJyw0ri0gNT4gLTFqMS0-j0lNQUOQMjAyMy4zLjE2kUI

2024 Intermediate Alternate Known  https://openaero.net/?s=hEludGVybWVkaWF0ZYUyMDI0IEFsdCBLbm93bodwb3dlcmVkiEtub3duiUlNQUONMyUgLTZgZzI0IDJpeTEtIDE0JSA0PiAt4CxpZmE0OCwyK-AgKDAsMTQpICxpZnpiLqcssiA3PiC0aC4yrictIDg-IC1vMjQgNj4gLyw4cGIsZq4uLeAgMiUgND4gLXY1IGl24GA3cycsNK4tIDEzPiAtLqdrj0lNQUOQMjAyMy4zLjE2kUI

2024 Advanced Known  https://openaero.net/?s=hEFkdmFuY2VkhTIwMjQgS25vd26HcG93ZXJlZIhLbm93bolJTUFDjS8usnngLDVmri1eIDglID4gLTNqMy0gKDEwLDMpIC0uNDguJ3JkYi4sNmlmri4r4ODg4GAgpyA2PiBvMjQsMS0gOD4gLSwzaWZw4igyLicpJywzNC0gMjE-IK3gYDdpcyw4rqdpcvAtIDclIDc-IC3g4OBgaWPgYDUsNODg4GArYCAyPiCuLic2Zq6uLqdpdC4zpywzZn4gMTAlIDI2PiAsZmG4LSA3PiAtpzgsM2gnM2anLV6PSU1BQ5AyMDIzLjMuMTaRQg

2024 Advanced Alternate Known  https://openaero.net/?s=hEFkdmFuY2Vkh3Bvd2VyZWSIS25vd26JSU1BQ40vsnngLDVmLi1eIDElIDc-IC0yNKdiri4zpy0gNT4gLTQ4J3JkYi4nNmlmrqcr4ODgYCBvMjQsMS0gLSwzaWZw4igyLicpJywzNC0gMjc-IK3gYDdpcyw4rqdpcvAtIDclIDEyPiAt4ODgYGlj4GA1LDTg4OBgK2AgMj4gri42Zq6uLidpdC4zpywzZn4gMTAlIDI0PiAsZmG4LSA1PiAtpzgsM2gnM2anLV6PSU1BQ5AyMDIzLjMuMTaRQg

2024 Unlimited Known  https://openaero.net/?s=hFVubGltaXRlZIUyMDI0IEtub3duh3Bvd2VyZWSIS25vd26JSU1BQ40zJSDg4OA4LDdmLnFgsqctILE-IC0nNCw1aWYnaC4nLDI0LicrfiAzJSAxMD4gNGpvaTI-IDc-IDMlIDMsMzRtNmlm_iAoMCwxNykgLiw3aWYsNKdpemIupyy0Lict_iAoMiwxNCkgMTYlIOAt4OBgN2lz4ODgLGZpYkIo4ODgOWbgYCmuNytgXiAzJSA0PiBvODs1Zi0gMiUgMz4gLSw0OHQuJzUsM2lmriAyJSA5PiAsMzJ54OAsMjQ7aWYuIDY-IDZmYywyNCwxLY9JTUFDkDIwMjMuMy4xNpFC

2024 Unlimited Alternate Known  https://openaero.net/?s=hFVubGltaXRlZIUyMDI0IEtub3duIEFsdGVybmF0ZYdwb3dlcmVkiEtub3duiUlNQUONMyUg4ODgOCw3Zi5xYLKnLSAxMj4gLSc0LDVpZidori4nLDI0rit-IDMlIDc-IHJwKDYsNmlmKSwxIDc-IDMlIDMsMzRtNmlm_iAoMSwyMSkgLiw3aWYsNKdpemIupyy0Lict_iAoMiyxKSAxNiUg4C3g4GA3aXPg4OAsZmliQijg4OA5ZuBgKa43K2BeIDMlIDQ-IG84OzVmLSAyJSA0PiAtLDQ4dC4nNSwzaWYupyAyJSA5PiAsMzJ54OAsMjQ7aWYnIDU-IDZmYywyNCwxLY9JTUFDkDIwMjMuMy4xNpFC

**Comment by OpenAero** [comment]
Sorry, forgot to add these in the 2024.1.3 release. Will add to the next release, expected within a month.

**Comment by Bdavy92960** [comment]
Any status on getting the 2024 IMAC knowns into the released version library?

Brad

**Comment by OpenAero** [comment]
Sorry, very busy so it's taking all somewhat longer. Hopefully within a few weeks.

**Comment by OpenAero** [comment]
Finally released 2024.1.4, with these sequences included. Sorry for the delay.
