### ISSUE TITLE
Urgent - IMAC Rules file not active when selecting Advanced and Unlimited

### ISSUE THREAD

**Issue by Bdavy92960** [OpenAero/main#287]
In version 2025.1.1When selecting IMAC Advanced or Unknown, there is a warning that No Sequence Validity checking rules active.  This behavior was noted in the devel version, but not reported.  

Brad

**Comment by OpenAero** [comment]
Thank you for the warning. I have released a new version on openaero.net (you may need to reload twice) that should fix this. If you let me know that there are no more issues with the fix, I will also release it for the app versions.

**Comment by OpenAero** [comment]
Fixed in 2025.1.2
