### ISSUE TITLE
Improve Chandelle look

### ISSUE THREAD

**Issue by GoogleCodeExporter** [OpenAero/main#63]
```
Your chandelle/wingover appearance is a bit strange. In BAeA we require a 45° 
line of some length to be drawn before the co-ordinated roll/pull to horizontal 
then opposite direction roll/pull back down to the 45°, whereas IAC have no 
45° lines and the pulls are co-ordinated segments from the start. Could you do 
something like this? I doubt it would ever get to be a cross-box figure, but 
you never know ...
```

Original issue reported on code.google.com by `openaero...@gmail.com` on 28 May 2013 at 8:45

Attachments:
- [Chandelle.png](https://storage.googleapis.com/google-code-attachments/open-aero/issue-63/comment-0/Chandelle.png)

**Comment by OpenAero** [comment]
Changed wingover shape to show 1/8 loop entry and exit curve in 2024.1.4. Really not much more to do about this and a vary minor issue. Closing.
