### ISSUE TITLE
/ to change the slope of the y axis for a single figure

### ISSUE THREAD

**Issue by GoogleCodeExporter** [OpenAero/main#69]
```
What steps will reproduce the problem?
1. open olan and select a figure that transitions from the x to y axis
2. under the base figure selection box, there are 3 buttons at the left and 3 
buttons at the right. the left button in the right group of 3 can be used to 
change the slop of the y axis from [top right to bottom left] to ]top right to 
bottom left]. the change is cosmetic only but is very useful in making form b 
look good

in olan, clicking this button adds a "/" after the figure letters. in open aero 
the same "/" has a different effect. it changes the y axis direction for the 
whole sequence only and also changes it from [top right to bottom left] to 
[bottom left to top right].

the way open aero does this is never used. 

The sequence on form b always flows left to right, then, if there is a x box y 
axis exit figure, top to bottom (never bottom to top). then it flows back right 
to left. all y axis exits are top to bottom otherwise you end up drawing back 
on top of previous figures.

Thanks Ringo,

Regards

Dave


What version of the product are you using? On what operating system?

1.3.0 windows 7


Please provide any additional information below.

your'e doing a great job. I really appreciate it. I've introduced lots of 
australian flyers to open aero and they have all shown a lot of interest as it 
being a better product than what they are using.


```

Original issue reported on code.google.com by `D...@davidfoordavionics.com.au` on 1 Jun 2013 at 9:17

**Comment by OpenAero** [comment]
To provide a consistent use and prevent misuse (bad sequence design) of Y-axis direction switching, the following logic seems appropriate:

1) a button will be added to the Figure Editor to change Y-axis direction
2) the Y-axis of figures that are preceded by a figure ending on Y-axis is the same as preceding
3) the Y direction stays consistent throughout the figure
4) when using the Figure Editor button, the current figure's Y-axis direction is changed. If there are figures after this one, their Y-axis direction is kept as before unless 2) applies
5) when using Sequence/Flip Y-axis the entire sequence's Y direction is changed

**Comment by nickbuck** [comment]
I have a few recent Visio Aresti sequence diagrams that make good use of mixed down-left and down-right Y axis figure in/out legs, but none that go up/right or up/left which I think should be avoided. If an individual figure down left/right option were available it would for sure help in the layout of some sequence designs, and if done in a neat/tidy manner I would vote for it.

![image](https://cloud.githubusercontent.com/assets/3930581/9905907/8da35318-5c7f-11e5-89f4-be1d9a57c4ad.png)

![image](https://cloud.githubusercontent.com/assets/3930581/9905931/b00b7d90-5c7f-11e5-90e6-4d67cc0a0f8b.png)

![image](https://cloud.githubusercontent.com/assets/3930581/9905947/c05dd27e-5c7f-11e5-9066-9b16713c2718.png)

Nick B

**Comment by OpenAero** [comment]
Completed on OpenAero 2016.2.

Exception form planned logic:
4) when using the Figure Editor button, the current figure's Y-axis direction is changed. If there are figures after this one, their Y-axis direction is also changed

This prevents a preference for different Y-axis directions to occur. Sequence designers should actively change subsequent Y axis directions.
