### ISSUE TITLE
Add save PDF button

### ISSUE THREAD

**Issue by GoogleCodeExporter** [OpenAero/main#95]
```
Many people seem to have problems with the save as .pdf function. Too many 
clicks for the non-computer-persons. Maybe a simple button on the main page 
would help?
This is quite important, because you should check in at a championship with a 
.pdf file – so everybody needs this function.

This may be done by using jsPDF (jspdf.com) to add the svg sequence images to a 
PDF directly without going through Chrome's print dialog.
```

Original issue reported on code.google.com by `openaero...@gmail.com` on 26 Jun 2013 at 9:55

**Comment by OpenAero** [comment]
This may be useful:
http://www.sitepoint.com/generating-pdfs-from-web-pages-on-the-fly-with-jspdf/

**Comment by OpenAero** [comment]
As of 2022.2.5:
* Direct save to PDF from iOS app
* Save as PDF from print dialog working well in all other apps and browser
* jsPDF still has some issues with correct formatting

Therefore, current solution works well for all systems. Closing this issue.
